Add support for pocket+imx8mp, pocket+a311d, reform+imx8mp and reform+rk3588
Refactor codebase to make use of config files instead of letting every
script re-implement the same logic over and over again.

With this commit, eight boards are supported:

 - MNT Reform 2
 - MNT Reform 2 HDMI
 - MNT Reform 2 with BPI-CM4 Module
 - MNT Reform 2 with LS1028A Module
 - MNT Reform 2 with RCORE RK3588 Module
 - MNT Reform 2 with i.MX8MP Module
 - MNT Pocket Reform with BPI-CM4 Module
 - MNT Pocket Reform with i.MX8MP Module

diff --git a/bin/reform-check b/bin/reform-check
--- a/bin/reform-check
+++ b/bin/reform-check
@@ -56,6 +56,16 @@ else
 	MIRROR="mntre.com"
 fi
 
+# shellcheck source=/dev/null
+if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "./machines/$(cat /proc/device-tree/model).conf"
+elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+else
+	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+	exit 1
+fi
+
 if [ ! -e "/etc/flash-kernel/machine" ]; then
 	# /etc/flash-kernel/machine not existing is only a potential problem
 	# on imx8mq
@@ -116,53 +126,25 @@ if [ -z "$(findmnt --fstab --noheadings --evaluate --mountpoint / --output SOURC
 	echo "$(findmnt --noheadings --evaluate --mountpoint / --output SOURCE) / auto errors=remount-ro 0 1" >&2
 fi
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") MMCDEV="mmcblk0"; SDDEV="mmcblk1" ;;
-	"MNT Reform 2 with BPI-CM4 Module")                   SDDEV="mmcblk0" ;;
-	"MNT Reform 2 with LS1028A Module") MMCDEV="mmcblk1"; SDDEV="mmcblk0" ;;
-esac
-
-
 if [ -z "$(findmnt --fstab --noheadings --evaluate --mountpoint /boot --output SOURCE)" ]; then
 	echo "E: your /etc/fstab does not have an entry for /boot" >&2
-	case "$(cat /proc/device-tree/model)" in
-		"MNT Reform 2"|"MNT Reform 2 HDMI"|"MNT Reform 2 with LS1028A Module")
-			echo "E: for eMMC booting, add:" >&2
-			echo "/dev/${MMCDEV}p1 /boot auto errors=remount-ro 0 1" >&2
-			;;
-	esac
+	if [ "$EMMC_BOOT" = true ]; then
+		echo "E: for eMMC booting, add:" >&2
+		echo "/dev/${DEV_MMC}p1 /boot auto errors=remount-ro 0 1" >&2
+	fi
 	echo "E: for SD-Card booting, add:" >&2
-	echo "/dev/${SDDEV}p1 /boot auto errors=remount-ro 0 1" >&2
+	echo "/dev/${DEV_SD}p1 /boot auto errors=remount-ro 0 1" >&2
 fi
 
 if ! mountpoint --quiet /boot; then
 	echo "E: your /boot has nothing mounted on it -- fix your /etc/fstab" >&2
 fi
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI")
-		ubootsha1="3de987054676b65b80ecb65455465326c9539928"
-		ubootproject="reform-boundary-uboot"
-		uboottag="2023-10-18"
-		;;
-	"MNT Reform 2 with BPI-CM4 Module")
-		ubootsha1="db5f2efb62da58dbf548e73a97764cc1380ed4ab"
-		ubootproject="reform-a311d-uboot"
-		uboottag="2023-10-18"
-		;;
-	"MNT Reform 2 with LS1028A Module")
-		ubootsha1="41570d83a25e8fb6ec84afa1e4cc9559c962d621"
-		ubootproject="reform-ls1028a-uboot"
-		uboottag="2023-10-10"
-		;;
-	*) echo "E: unexpected content in /proc/device-tree/model" >&2 ;;
-esac
-
 # FIXME: on ls1028a, also check for /boot/ls1028a-mhdpfw.bin
 
-ubooturl="https://source.mnt.re/reform/${ubootproject}/-/jobs/artifacts/${uboottag}/raw/flash.bin?job=build"
+ubooturl="https://source.mnt.re/reform/${UBOOT_PROJECT}/-/jobs/artifacts/${UBOOT_TAG}/raw/flash.bin?job=build"
 ubootbin=$(mktemp)
-/usr/lib/apt/apt-helper download-file "$ubooturl" "$ubootbin" "SHA1:$ubootsha1" >/dev/null
+/usr/lib/apt/apt-helper download-file "$ubooturl" "$ubootbin" "SHA1:$UBOOT_SHA1" >/dev/null
 if [ ! -e /boot/flash.bin ]; then
 	echo "W: /boot/flash.bin doesn't exist" >&2
 	echo "W: You can download the latest version by running as root:" >&2
@@ -172,22 +154,15 @@ elif ! cmp --quiet /boot/flash.bin "$ubootbin"; then
 	echo "W: You can update it to the latest version by running as root:" >&2
 	echo "reform-flash-uboot" >&2
 fi
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") ubootoffset=$((1024*33)); flashbinoffset=0;;
-	"MNT Reform 2 with BPI-CM4 Module") ubootoffset=512;          flashbinoffset=512;;
-	"MNT Reform 2 with LS1028A Module") ubootoffset=$((512*8));   flashbinoffset=0;;
-esac
 ubootsize=$(stat --format=%s "$ubootbin")
 
-case "$(cat /proc/device-tree/model)" in "MNT Reform 2"|"MNT Reform 2 HDMI")
-	if ! cmp --quiet --bytes="$ubootsize" "--ignore-initial=$flashbinoffset:$ubootoffset" "$ubootbin" "/dev/${MMCDEV}boot0" 2>/dev/null; then
-		echo "W: eMMC does not contain latest uboot" >&2
-		echo "W: You can update it to the latest version by running as root:" >&2
-		echo "reform-flash-uboot emmc" >&2
-	fi
-	;;
-esac
-if [ -e "/dev/$SDDEV" ] && ! cmp --quiet --bytes="$ubootsize" --ignore-initial="0:$ubootoffset" "$ubootbin" "/dev/$SDDEV" 2>/dev/null; then
+if [ "$EMMC_BOOT" = true ] && ! cmp --quiet --bytes="$ubootsize" "--ignore-initial=$FLASHBIN_OFFSET:$UBOOT_OFFSET" "$ubootbin" "/dev/${DEV_MMC}boot0" 2>/dev/null; then
+	echo "W: eMMC does not contain latest uboot" >&2
+	echo "W: You can update it to the latest version by running as root:" >&2
+	echo "reform-flash-uboot emmc" >&2
+fi
+
+if [ -e "/dev/$DEV_SD" ] && ! cmp --quiet --bytes="$ubootsize" --ignore-initial="0:$UBOOT_OFFSET" "$ubootbin" "/dev/$DEV_SD" 2>/dev/null; then
 	echo "W: SD-Card does not contain latest uboot" >&2
 	echo "W: You can update it to the latest version by running as root:" >&2
 	echo "reform-flash-uboot sd" >&2
@@ -212,15 +187,12 @@ case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with LS1028A Module")
 	;;
 esac
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI"|"MNT Reform 2 with LS1028A Module")
-		if [ ! -e "/dev/${MMCDEV}p2" ]; then
-			echo "W: /dev/${MMCDEV}p2 doesn't exist." >&2
-			echo "W: To update your eMMC to sysimage-v4 you can run reform-flash-rescue" >&2
-			echo "W: Only run reform-flash-rescue if you intend a factory-reset of your eMMC" >&2
-			echo "W: Do not use reform-flash-rescue if you boot from eMMC because this will overwrite your /boot partition" >&2
-		fi
-esac
+if [ "$EMMC_USE" = true ] && [ ! -e "/dev/${DEV_MMC}p2" ]; then
+	echo "W: /dev/${DEV_MMC}p2 doesn't exist." >&2
+	echo "W: To update your eMMC to sysimage-v4 you can run reform-flash-rescue" >&2
+	echo "W: Only run reform-flash-rescue if you intend a factory-reset of your eMMC" >&2
+	echo "W: Do not use reform-flash-rescue if you boot from eMMC because this will overwrite your /boot partition" >&2
+fi
 
 if [ ! -e /etc/flash-kernel/machine ]; then
 	# /etc/flash-kernel/machine not existing is only a potential problem
@@ -327,8 +299,7 @@ esac
 
 # on a311d we need non-free-firmware
 # shellcheck disable=SC2016
-if [ "$(tr -d '\0' < /proc/device-tree/model)" = "MNT Reform 2 with BPI-CM4 Module" ] \
-	&& ! apt-get indextargets 'Created-By: Packages' 'Origin: Debian' 'Repo-URI: http://deb.debian.org/debian/' --format '$(COMPONENT)' | sort -u | grep --silent non-free-firmware; then
+if [ "$NEED_NONFREE" = true ] && ! apt-get indextargets 'Created-By: Packages' 'Origin: Debian' 'Repo-URI: http://deb.debian.org/debian/' --format '$(COMPONENT)' | sort -u | grep --silent non-free-firmware; then
 	echo "W: you do not have non-free-firmware enabled" >&2
 	echo "W: this is required to install non-free firmware blobs that are required for platforms like Banana Pi A311D" >&2
 	echo "W: you can add a line like this to your /etc/apt/sources.list:" >&2
diff --git a/sbin/reform-boot-config b/sbin/reform-boot-config
--- a/sbin/reform-boot-config
+++ b/sbin/reform-boot-config
@@ -26,32 +26,37 @@ fi
 echo "This script selects your preferred boot medium. It writes your choice to the file /etc/fstab"
 echo
 
-case $(cat /proc/device-tree/model) in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") MMCDEV="mmcblk0"; SDDEV="mmcblk1"; NVMEDEV=nvme0n1; USBDEV=sda ;;
-	"MNT Reform 2 with BPI-CM4 Module")                   SDDEV="mmcblk0"; NVMEDEV=nvme0n1; USBDEV=sda ;;
-	"MNT Reform 2 with LS1028A Module") MMCDEV="mmcblk1"; SDDEV="mmcblk0"; NVMEDEV=sda;     USBDEV=sdb ;;
-	*) echo "E: unknown platform: $(cat /proc/device-tree/model)" >&2; exit 1;;
-esac
+# shellcheck source=/dev/null
+if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "./machines/$(cat /proc/device-tree/model).conf"
+elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+else
+	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+	exit 1
+fi
 
 usage() {
 	echo "Usage: " >&2
-	echo "  reform-boot-config [--emmc] sd    # rootfs on SD card (/dev/${SDDEV}p2, default)." >&2
-	echo "  reform-boot-config [--emmc] nvme  # rootfs on NVMe SSD (/dev/${NVMEDEV}p1)." >&2
-	echo "  reform-boot-config [--emmc] usb   # rootfs on USB storage device (/dev/${USBDEV}1)." >&2
-	case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with BPI-CM4 Module")
-		echo "Choosing sd, nvme, or usb  will set the root partition to" >&2
-		echo "/dev/${SDDEV}p2, /dev/${NVMEDEV}p1 or /dev/${USBDEV}1," >&2
-		;;
-	*)
-		echo "  reform-boot-config [--emmc] emmc  # rootfs on eMMC (/dev/${MMCDEV}p2)." >&2
+	if [ "$EMMC_USE" = true ]; then
+		echo "  reform-boot-config [--emmc] sd    # rootfs on SD card (/dev/${DEV_SD}p2, default)." >&2
+		echo "  reform-boot-config [--emmc] nvme  # rootfs on NVMe SSD (/dev/${DEV_SSD}p1)." >&2
+		echo "  reform-boot-config [--emmc] usb   # rootfs on USB storage device (/dev/${DEV_USB}1)." >&2
+		echo "  reform-boot-config [--emmc] emmc  # rootfs on eMMC (/dev/${DEV_MMC}p2)." >&2
 		echo "" >&2
 		echo "      --emmc Record boot preference on eMMC instead of SD card." >&2
 		echo "             This is only useful with SoM dip switch turned off." >&2
 		echo "" >&2
 		echo "Choosing sd, nvme, usb or emmc will set the root partition to" >&2
-		echo "/dev/${SDDEV}p2, /dev/${NVMEDEV}p1, /dev/${USBDEV}1 or /dev/${MMCDEV}p2," >&2
-		;;
-	esac
+		echo "/dev/${DEV_SD}p2, /dev/${DEV_SSD}p1, /dev/${DEV_USB}1 or /dev/${DEV_MMC}p2," >&2
+	else
+		echo "  reform-boot-config sd    # rootfs on SD card (/dev/${DEV_SD}p2, default)." >&2
+		echo "  reform-boot-config nvme  # rootfs on NVMe SSD (/dev/${DEV_SSD}p1)." >&2
+		echo "  reform-boot-config usb   # rootfs on USB storage device (/dev/${DEV_USB}1)." >&2
+		echo "" >&2
+		echo "Choosing sd, nvme, or usb  will set the root partition to" >&2
+		echo "/dev/${DEV_SD}p2, /dev/${DEV_SSD}p1 or /dev/${DEV_USB}1," >&2
+	fi
 	echo "respectively. You can choose another root partition by passing" >&2
 	echo "the absolute device path starting with /dev/ explicitly." >&2
 	echo "For example, to boot a rootfs on an LVM volume, run:" >&2
@@ -65,17 +70,16 @@ if [ $# -ne 1 ] && [ $# -ne 2 ]; then
 fi
 
 BOOTPREF="$1"
-BOOTPART="${SDDEV}p1"
+BOOTPART="${DEV_SD}p1"
 
 if [ "--emmc" = "$1" ]; then
-	case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with BPI-CM4 Module")
-		echo "E: writing to eMMC not supported on A311D" >&2
+	if [ "$EMMC_USE" = false ]; then
+		echo "E: writing to eMMC not supported on $(cat /proc/device-tree/model)" >&2
 		exit 1
-		;;
-	esac
+	fi
 
 	BOOTPREF="$2"
-	BOOTPART="${MMCDEV}p1"
+	BOOTPART="${DEV_MMC}p1"
 
 	if [ ! -b "/dev/$BOOTPART" ]; then
 		echo "/dev/$BOOTPART doesn't exist -- run reform-flash-rescue" >&2
@@ -84,10 +88,10 @@ if [ "--emmc" = "$1" ]; then
 fi
 
 case $BOOTPREF in
-	sd)   : "${ROOTPART:=${SDDEV}p2}";;
-	nvme) : "${ROOTPART:=${NVMEDEV}p1}";;
-	usb)  : "${ROOTPART:=${USBDEV}1}";;
-	emmc) : "${ROOTPART:=${MMCDEV}p2}";;
+	sd)   : "${ROOTPART:=${DEV_SD}p2}";;
+	nvme) : "${ROOTPART:=${DEV_SSD}p1}";;
+	usb)  : "${ROOTPART:=${DEV_USB}1}";;
+	emmc) : "${ROOTPART:=${DEV_MMC}p2}";;
 	/dev/*)
 		if [ ! -b "$BOOTPREF" ]; then
 			echo "there is no block device called $BOOTPREF" >&2
@@ -183,7 +187,7 @@ if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$BOOTPART")" ]; then
 	# or it doesn't have the reformsdboot label
 	# then immediately exit
 	if [ "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$BOOTPART")" != "/boot" ] \
-		|| [ "$BOOTPART" != "${SDDEV}p1" ] \
+		|| [ "$BOOTPART" != "${DEV_SD}p1" ] \
 		|| [ "$(lsblk --noheadings --output=LABEL "/dev/$BOOTPART")" != "reformsdboot" ]; then
 		echo "Please unmount before running this script" >&2
 		exit 1
@@ -286,12 +290,12 @@ trap - EXIT INT TERM
 # or reformemmcboot labels in case it used to be the /boot partition from a
 # rescue system on sd-card or emmc, respectively
 case "$BOOTPART" in
-	"${SDDEV}p1")
+	"${DEV_SD}p1")
 		if [ "$(lsblk --noheadings --output=LABEL "/dev/$BOOTPART")" = "reformsdboot" ]; then
 			e2label "/dev/$BOOTPART" ""
 		fi
 		;;
-	"${MMCDEV}p1")
+	"${DEV_MMC}p1")
 		if [ "$(lsblk --noheadings --output=LABEL "/dev/$BOOTPART")" = "reformemmcboot" ]; then
 			e2label "/dev/$BOOTPART" ""
 		fi
@@ -304,14 +308,14 @@ if [ "$MOUNTROOT" = "/" ]; then
 	mount /boot
 fi
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2 with BPI-CM4 Module") echo "Your /boot partition is on your SD-Card (/dev/$BOOTPART)." >&2 ;;
-	*)	if [ "$BOOTPART" = "${MMCDEV}p1" ]; then
-			echo "Your /boot partition is on emmc (/dev/$BOOTPART)." >&2
-		else
-			echo "Your /boot partition is on your SD-Card (/dev/$BOOTPART)." >&2
-		fi
-	;;
-esac
+if [ "$EMMC_USE" = true ]; then
+	if [ "$BOOTPART" = "${DEV_MMC}p1" ]; then
+		echo "Your /boot partition is on emmc (/dev/$BOOTPART)." >&2
+	else
+		echo "Your /boot partition is on your SD-Card (/dev/$BOOTPART)." >&2
+	fi
+else
+	echo "Your /boot partition is on your SD-Card (/dev/$BOOTPART)." >&2
+fi
 
 echo "Restart MNT Reform (type: reboot) after saving your work to activate the changes."
diff --git a/sbin/reform-flash-rescue b/sbin/reform-flash-rescue
--- a/sbin/reform-flash-rescue
+++ b/sbin/reform-flash-rescue
@@ -1,23 +1,30 @@
 #!/bin/sh
 
-set -e
+set -eu
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") : ;;
-	"MNT Reform 2 with BPI-CM4 Module") echo "E: refusing to modify eMMC on A311D" >&2; exit 1;;
-	"MNT Reform 2 with LS1028A Module") : ;;
-	*) echo "E: unknown platform: $(cat /proc/device-tree/model)" >&2; exit 1;;
-esac
+# shellcheck source=/dev/null
+if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "./machines/$(cat /proc/device-tree/model).conf"
+elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+else
+	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+	exit 1
+fi
 
-# only run "reform-flash-uboot emmc" on imx8mq
-case "$(cat /proc/device-tree/model)" in "MNT Reform 2"|"MNT Reform 2 HDMI")
-	if [ ! -e /sys/class/block/mmcblk0boot0/force_ro ]; then
-		echo "/sys/class/block/mmcblk0boot0/force_ro doesn't exist" >&2
+if [ "$EMMC_USE" = false ]; then
+	echo "E: writing to eMMC not supported on $(cat /proc/device-tree/model)" >&2
+	exit 1
+fi
+
+if [ "$EMMC_BOOT" = true ]; then
+	if [ ! -e "/sys/class/block/${DEV_MMC}boot0/force_ro" ]; then
+		echo "/sys/class/block/${DEV_MMC}boot0/force_ro doesn't exist" >&2
 		exit 1
 	fi
 
-	if [ ! -w /sys/class/block/mmcblk0boot0/force_ro ]; then
-		echo "/sys/class/block/mmcblk0boot0/force_ro is not writable" >&2
+	if [ ! -w "/sys/class/block/${DEV_MMC}boot0/force_ro" ]; then
+		echo "/sys/class/block/${DEV_MMC}boot0/force_ro is not writable" >&2
 		exit 1
 	fi
 
@@ -26,7 +33,7 @@ case "$(cat /proc/device-tree/model)" in "MNT Reform 2"|"MNT Reform 2 HDMI")
 		exit 1
 	fi
 
-	for p in $(lsblk --list --noheadings --output=NAME /dev/mmcblk0) mmcblk0boot0 mmcblk0boot1; do
+	for p in $(lsblk --list --noheadings --output=NAME "/dev/$DEV_MMC") "${DEV_MMC}boot0" "${DEV_MMC}boot1"; do
 		[ -b "/dev/$p" ] || continue
 		if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$p")" ]; then
 			echo "/dev/$p is still in use" >&2
@@ -47,10 +54,9 @@ case "$(cat /proc/device-tree/model)" in "MNT Reform 2"|"MNT Reform 2 HDMI")
 
 	reform-flash-uboot --offline emmc
 
-	echo "Bootloader was successfully written to /dev/mmcblk0boot0." >&2
+	echo "Bootloader was successfully written to /dev/${DEV_MMC}boot0." >&2
 	echo "" >&2
-	;;
-esac
+fi
 
 echo "Do you want to download and install the latest sysimage-v4 to eMMC as well?" >&2
 echo "This step needs a working internet connection and either wget or curl installed." >&2
@@ -65,14 +71,7 @@ if [ "$response" != "y" ]; then
 	exit
 fi
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") PLATFORM=imx8mq ;;
-	"MNT Reform 2 with BPI-CM4 Module") echo "E: refusing to modify eMMC on A311D" >&2; exit 1;;
-	"MNT Reform 2 with LS1028A Module") PLATFORM=ls1028a ;;
-	*) echo "E: unknown platform: $(cat /proc/device-tree/model)" >&2; exit 1;;
-esac
-
-URL="https://source.mnt.re/reform/reform-system-image/-/jobs/artifacts/main/raw/reform-system-${PLATFORM}.img.gz?job=build"
+URL="https://source.mnt.re/reform/reform-system-image/-/jobs/artifacts/main/raw/${SYSIMAGE}.img.gz?job=build"
 DECOMPRESSOR=gzip
 
 if grep --silent '^URIs: https://reform.debian.net/debian/\?$' /etc/apt/sources.list.d/reform*.sources 2>/dev/null; then
@@ -86,17 +85,12 @@ if grep --silent '^URIs: https://reform.debian.net/debian/\?$' /etc/apt/sources.
 	if [ "$response" = "y" ]; then
 		# no need to use the backports kernel because a311d is not
 		# allowed to write to emmc anyways
-		URL="https://reform.debian.net/images/reform2-system-${PLATFORM}.img.xz"
+		URL="https://reform.debian.net/images/${SYSIMAGE}.img.xz"
 		DECOMPRESSOR=xz
 	fi
 fi
 
 echo "Downloading $URL..."
-
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") MMCDEV="mmcblk0";;
-	"MNT Reform 2 with LS1028A Module") MMCDEV="mmcblk1";;
-esac
 
 {
 if curl --version >/dev/null; then
@@ -106,12 +100,12 @@ elif wget --version >/dev/null; then
 else
 	echo "need curl or wget" >&2
 	exit 1
-fi; } | "$DECOMPRESSOR" --decompress --to-stdout | dd of="/dev/$MMCDEV" status=progress
-partprobe "/dev/$MMCDEV"
+fi; } | "$DECOMPRESSOR" --decompress --to-stdout | dd of="/dev/$DEV_MMC" status=progress
+partprobe "/dev/$DEV_MMC"
 
 # overwrite the partition label
-e2label "/dev/${MMCDEV}p1" reformemmcboot
-e2label "/dev/${MMCDEV}p2" reformemmcroot
+e2label "/dev/${DEV_MMC}p1" reformemmcboot
+e2label "/dev/${DEV_MMC}p2" reformemmcroot
 
 # The rescue system image that we downloaded and wrote to the eMMC above is
 # configured to use the rootfs on the SD-Card but we want the initramfs on eMMC
diff --git a/sbin/reform-flash-uboot b/sbin/reform-flash-uboot
--- a/sbin/reform-flash-uboot
+++ b/sbin/reform-flash-uboot
@@ -2,56 +2,49 @@
 
 set -eu
 
-# disallow writing u-boot to eMMC on A311D and LS1028A
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2 with BPI-CM4 Module")
-		for dev in "$@"; do case $dev in emmc|"/dev/mmcblk1"*)
-			echo "Unless you know what you are doing, you might want to refrain" >&2
-			echo "from utilizing the eMMC on A311D Banana Pi because if something" >&2
-			echo "goes wrong, it will be hard to un-brick your board." >&2
-			exit 1
-			;;
-		esac; done ;;
-	"MNT Reform 2 with LS1028A Module")
-		for dev in "$@"; do case $dev in emmc|"/dev/mmcblk1"*)
-			echo "The LS1028A currently is only able to load u-boot from SD-Card." >&2
-			exit 1
-			;;
-		esac; done ;;
-esac
+# shellcheck source=/dev/null
+if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "./machines/$(cat /proc/device-tree/model).conf"
+elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+else
+	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+	exit 1
+fi
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") MMCDEV="mmcblk0"; SDDEV="mmcblk1" ;;
-	"MNT Reform 2 with BPI-CM4 Module")                   SDDEV="mmcblk0" ;;
-	"MNT Reform 2 with LS1028A Module")                   SDDEV="mmcblk0" ;;
-	*) echo "Unknown device name: $(cat /proc/device-tree/model)" >&2; exit 1;;
-esac
+if [ "$EMMC_BOOT" = false ]; then
+	for dev in "$@"; do
+		case $dev in emmc|"/dev/${DEV_MMC}"*)
+			echo "E: writing uboot to eMMC not supported on $(cat /proc/device-tree/model)" >&2
+			exit 1
+			;;
+		esac
+	done
+fi
 
 usage() {
 	echo "Usage: " >&2
 	echo "  reform-flash-uboot [--offline] [device...]" >&2
 	echo "" >&2
-	case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with BPI-CM4 Module"|"MNT Reform 2 with LS1028A Module")
-		echo "Download and write recent uboot to SD-Card." >&2 ;;
-	*)
-		echo "Download and write recent uboot to eMMC or SD-Card." >&2 ;;
-	esac
+	if [ "$EMMC_BOOT" = true ]; then
+		echo "Download and write recent uboot to eMMC or SD-Card." >&2
+	else
+		echo "Download and write recent uboot to SD-Card." >&2
+	fi
 	echo "Without arguments only /boot/flash.bin will be updated unless --offline is given." >&2
 	echo "Otherwise, the arguments are the devices onto which to install uboot." >&2
-	case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with BPI-CM4 Module"|"MNT Reform 2 with LS1028A Module")
-		echo "A device shortcut is provided:" >&2
-		echo "" >&2
-		echo "   sd -> /dev/${SDDEV}" >&2
-		echo "" >&2
-		;;
-	*)
+	if [ "$EMMC_BOOT" = true ]; then
 		echo "Two device shortcuts are provided:" >&2
 		echo "" >&2
 		echo "   emmc -> /dev/${MMCDEV}boot0" >&2
 		echo "   sd -> /dev/${SDDEV}" >&2
 		echo "" >&2
-		;;
-	esac
+	else
+		echo "A device shortcut is provided:" >&2
+		echo "" >&2
+		echo "   sd -> /dev/${SDDEV}" >&2
+		echo "" >&2
+	fi
 }
 
 if [ "$#" -gt 0 ] && [ "$1" = "--help" ] || [ "$#" -eq 0 ] || [ "$1" = "-h" ]; then
@@ -64,30 +57,11 @@ if [ "$(id -u)" -ne 0 ]; then
 	exit 1
 fi
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI")
-		ubootsha1="3de987054676b65b80ecb65455465326c9539928"
-		ubootproject="reform-boundary-uboot"
-		uboottag="2023-10-18"
-		;;
-	"MNT Reform 2 with BPI-CM4 Module")
-		ubootsha1="db5f2efb62da58dbf548e73a97764cc1380ed4ab"
-		ubootproject="reform-a311d-uboot"
-		uboottag="2023-10-18"
-		;;
-	"MNT Reform 2 with LS1028A Module")
-		ubootsha1="41570d83a25e8fb6ec84afa1e4cc9559c962d621"
-		ubootproject="reform-ls1028a-uboot"
-		uboottag="2023-10-10"
-		;;
-	*) echo "E: unexpected content in /proc/device-tree/model" >&2; exit 1 ;;
-esac
-
 if [ "$#" -eq 0 ] || [ "$1" != "--offline" ]; then
 	echo "Downloading uboot to /boot/flash.bin and comparing checksum" >&2
 
-	ubooturl="https://source.mnt.re/reform/${ubootproject}/-/jobs/artifacts/${uboottag}/raw/flash.bin?job=build"
-	/usr/lib/apt/apt-helper -oAPT::Sandbox::User=root download-file "$ubooturl" "/boot/flash.bin" "SHA1:$ubootsha1"
+	ubooturl="https://source.mnt.re/reform/${UBOOT_PROJECT}/-/jobs/artifacts/${UBOOT_TAG}/raw/flash.bin?job=build"
+	/usr/lib/apt/apt-helper -oAPT::Sandbox::User=root download-file "$ubooturl" "/boot/flash.bin" "SHA1:$UBOOT_SHA1"
 	# download mhdpfw.bin on ls1028a
 	case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with LS1028A Module")
 		/usr/lib/apt/apt-helper -oAPT::Sandbox::User=root download-file \
@@ -99,7 +73,7 @@ if [ "$#" -eq 0 ] || [ "$1" != "--offline" ]; then
 elif [ "$#" -gt 0 ] && [ "$1" = "--offline" ]; then
 	echo "Not downloading uboot but using /boot/flash.bin without updating it." >&2
 	shift
-	if ! echo "$ubootsha1  /boot/flash.bin" | sha1sum --strict --check >/dev/null 2>&1; then
+	if ! echo "$UBOOT_SHA1  /boot/flash.bin" | sha1sum --strict --check >/dev/null 2>&1; then
 		echo "Incorrect checksum for /boot/flash.bin" >&2
 		echo "Either flash manually, or run without --offline to download the latest uboot version" >&2
 		exit 1
@@ -111,12 +85,6 @@ if [ "$#" -eq 0 ]; then
 	exit 0
 fi
 
-# offsets given in multiples of 512 bytes
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") ubootoffset=66; flashbinoffset=0;;
-	"MNT Reform 2 with BPI-CM4 Module") ubootoffset=1;  flashbinoffset=1;;
-	"MNT Reform 2 with LS1028A Module") ubootoffset=8;  flashbinoffset=0;;
-esac
 ubootsize=$(stat --format=%s "/boot/flash.bin")
 
 # check if there is enough free space at the beginning of the disk
@@ -148,9 +116,9 @@ for dev in "$@"; do
 		exit 1
 	esac
 
-	if [ "$((512*(ubootoffset-flashbinoffset)+ubootsize))" -ge "$freeuntil" ]; then
+	if [ "$((UBOOT_OFFSET-FLASHBIN_OFFSET+ubootsize))" -ge "$freeuntil" ]; then
 		echo "the first partition on $dev starts at $freeuntil and would be overwritten by uboot" >&2
-		echo "make sure that the first $((512*(ubootoffset-flashbinoffset)+ubootsize)) bytes are free on $dev" >&2
+		echo "make sure that the first $((UBOOT_OFFSET-FLASHBIN_OFFSET+ubootsize)) bytes are free on $dev" >&2
 		exit 1
 	fi
 done
@@ -166,12 +134,12 @@ for dev in "$@"; do
 
 	if [ "$dev" = "/dev/${MMCDEV}boot0" ]; then
 		echo 0 > "/sys/class/block/${MMCDEV}boot0/force_ro"
-		dd if=/boot/flash.bin of="/dev/${MMCDEV}boot0" bs=512 seek="$ubootoffset" skip="$flashbinoffset"
+		dd if=/boot/flash.bin of="/dev/${MMCDEV}boot0" bs=512 seek="$((UBOOT_OFFSET/512))" skip="$((FLASHBIN_OFFSET/512))"
 		echo 1 > "/sys/class/block/${MMCDEV}boot0/force_ro"
 		continue
 	fi
 
-	dd if=/boot/flash.bin of="$dev" bs=512 seek="$ubootoffset" skip="$flashbinoffset"
+	dd if=/boot/flash.bin of="$dev" bs=512 seek="$((UBOOT_OFFSET/512))" skip="$((FLASHBIN_OFFSET/512))"
 done
 
 # inform about the DIP switch position only on imx8mq
diff --git a/sbin/reform-migrate b/sbin/reform-migrate
--- a/sbin/reform-migrate
+++ b/sbin/reform-migrate
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-set -e
+set -eu
 
 echo ""
 echo "This script can copy your current OS and files to a different disk, such as an SSD installed in MNT Reform."
@@ -18,47 +18,46 @@ echo ""
 echo "You can also setup an encrypted NVMe SSD by running reform-setup-encrypted-nvme"
 echo ""
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI") MMCDEV="mmcblk0"; SDDEV="mmcblk1" ;;
-	"MNT Reform 2 with BPI-CM4 Module")                   SDDEV="mmcblk0" ;;
-	"MNT Reform 2 with LS1028A Module") MMCDEV="mmcblk1"; SDDEV="mmcblk0" ;;
-	*) echo "E: unknown platform: $(cat /proc/device-tree/model)" >&2; exit 1;;
-esac
+# shellcheck source=/dev/null
+if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "./machines/$(cat /proc/device-tree/model).conf"
+elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+else
+	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+	exit 1
+fi
 
 usage() {
 	echo "Usage:"
-	case "$(cat /proc/device-tree/model)" in
-		"MNT Reform 2 with BPI-CM4 Module") echo "  reform-migrate TARGET" ;;
-		*) echo "  reform-migrate [--emmc] TARGET" ;;
-	esac
+	if [ "$EMMC_USE" = true ]; then
+		echo "  reform-migrate [--emmc] TARGET"
+	else
+		echo "  reform-migrate TARGET"
+	fi
 	echo ""
 	echo "Mounts TARGET and copies the currently running system to it using rsync. This will"
 	echo "overwrite all existing files in TARGET. At the end, reform-boot-config is run and"
-	case "$(cat /proc/device-tree/model)" in
-		"MNT Reform 2 with BPI-CM4 Module")
-			echo "will set up the first partition of the SD-card to load your newly copied rootfs"
-			echo "and adjust /etc/fstab of TARGET accordingly."
-			;;
-		*)
-			echo "will set up the first partition of the SD-card or eMMC (depending on the --emmc"
-			echo "option) to load your newly copied rootfs and adjust /etc/fstab of TARGET accordingly."
-			echo ""
-			echo "Options:"
-			echo ""
-			echo "      --emmc Record boot preference on eMMC instead of SD card."
-			echo "             This is only useful with SoM dip switch turned off."
-			;;
-	esac
+	if [ "$EMMC_USE" = true ]; then
+		echo "will set up the first partition of the SD-card or eMMC (depending on the --emmc"
+		echo "option) to load your newly copied rootfs and adjust /etc/fstab of TARGET accordingly."
+		echo ""
+		echo "Options:"
+		echo ""
+		echo "      --emmc Record boot preference on eMMC instead of SD card."
+		echo "             This is only useful with SoM dip switch turned off."
+	else
+		echo "will set up the first partition of the SD-card to load your newly copied rootfs"
+		echo "and adjust /etc/fstab of TARGET accordingly."
+	fi
 	echo ""
 	echo "Examples:"
 	echo ""
-	case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with BPI-CM4 Module") : ;;
-		*)
-			echo "  reform-migrate --emmc /dev/nvme0n1p1"
-			echo "          Mounts the first partition of an NVMe disk and mirrors your system to it."
-			echo "          Configures booting from the first partition on eMMC."
-			;;
-	esac
+	if [ "$EMMC_USE" = true ]; then
+		echo "  reform-migrate --emmc /dev/nvme0n1p1"
+		echo "          Mounts the first partition of an NVMe disk and mirrors your system to it."
+		echo "          Configures booting from the first partition on eMMC."
+	fi
 	echo "  reform-migrate /dev/mapper/crypt"
 	echo "          Mounts encrypted disk 'crypt' and mirrors your system to it."
 	echo "          The disk has to be unlocked first with: cryptsetup luksOpen /dev/nvme0n1p1 crypt"
@@ -72,17 +71,16 @@ fi
 
 EMMC=""
 TARGET="$1"
-BOOTPART="${SDDEV}p1"
+BOOTPART="${DEV_SD}p1"
 
 if [ "--emmc" = "$1" ]; then
-	case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with BPI-CM4 Module")
-		echo "E: writing to eMMC not supported on A311D" >&2
+	if [ "$EMMC_USE" = false ]; then
+		echo "E: writing to eMMC not supported on $(cat /proc/device-tree/model)" >&2
 		exit 1
-		;;
-	esac
+	fi
 	EMMC="--emmc"
 	TARGET="$2"
-	BOOTPART="${MMCDEV}p1"
+	BOOTPART="${DEV_MMC}p1"
 fi
 
 if [ -z "$TARGET" ]; then
diff --git a/sbin/reform-setup-encrypted-nvme b/sbin/reform-setup-encrypted-nvme
--- a/sbin/reform-setup-encrypted-nvme
+++ b/sbin/reform-setup-encrypted-nvme
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-set -e
+set -eu
 
 if [ "$(id -u)" -ne 0 ]; then
 	echo "reform-setup-encrypted-nvme has to be run as root / using sudo."
@@ -11,11 +11,21 @@ command -v "cryptsetup" >/dev/null 2>&1 || { echo >&2 "Please install \"cryptset
 command -v "lvchange" >/dev/null 2>&1 || { echo >&2 "Please install \"lvm2\" using: apt install lvm2"; exit 1; }
 command -v "mkfs.ext4" >/dev/null 2>&1 || { echo >&2 "Please install \"e2fsprogs\" using: apt install e2fsprogs"; exit 1; }
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI"|"MNT Reform 2 with BPI-CM4 Module") HUMAN="NVMe";;
-	"MNT Reform 2 with LS1028A Module")                                    HUMAN="SATA";;
-	*) echo "E: unknown platform: $(cat /proc/device-tree/model)" >&2; exit 1;;
-esac
+# shellcheck source=/dev/null
+if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "./machines/$(cat /proc/device-tree/model).conf"
+elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
+	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+else
+	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+	exit 1
+fi
+
+if [ "$DEV_SSD" = "sda" ]; then
+	HUMAN="SATA"
+else
+	HUMAN="NVMe"
+fi
 
 echo "This will ERASE ALL DATA from your $HUMAN SSD."
 
@@ -35,14 +45,8 @@ error() { echo "$0 FAILED to run" >&2; }
 
 trap error EXIT INT TERM
 
-case "$(cat /proc/device-tree/model)" in
-	"MNT Reform 2"|"MNT Reform 2 HDMI"|"MNT Reform 2 with BPI-CM4 Module") NVMEDEV=nvme0n1;;
-	"MNT Reform 2 with LS1028A Module")                                    NVMEDEV=sda;;
-	*) echo "E: unknown platform: $(cat /proc/device-tree/model)" >&2; exit 1;;
-esac
-
-if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$NVMEDEV")" ]; then
-	echo "/dev/$NVMEDEV is still in use" >&2
+if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$DEV_SSD")" ]; then
+	echo "/dev/$DEV_SSD is still in use" >&2
 	exit 1
 fi
 
@@ -59,9 +63,9 @@ if [ "$mem" -lt 4 ]; then
 	mem=4
 fi
 
-disksize=$(lsblk -bno SIZE "/dev/$NVMEDEV" | head -1)
+disksize=$(lsblk -bno SIZE "/dev/$DEV_SSD" | head -1)
 case "$disksize" in *[!0123456789]*|0?*|"")
-	echo "E: unable to acquire disk size of /dev/$NVMEDEV" >&2
+	echo "E: unable to acquire disk size of /dev/$DEV_SSD" >&2
 	exit 1
 esac
 # convert disk size to gigabytes, rounding down
@@ -77,9 +81,9 @@ if [ "$mem" -le 1 ]; then
 	exit 1
 fi
 
-cryptsetup luksFormat "/dev/$NVMEDEV"
+cryptsetup luksFormat "/dev/$DEV_SSD"
 trap "cleanupluks; error" EXIT INT TERM
-cryptsetup luksOpen "/dev/$NVMEDEV" reform_crypt
+cryptsetup luksOpen "/dev/$DEV_SSD" reform_crypt
 pvcreate /dev/mapper/reform_crypt
 vgcreate reformvg /dev/mapper/reform_crypt
 trap "cleanupvg; cleanupluks; error" EXIT INT TERM
@@ -88,7 +92,7 @@ mkswap /dev/reformvg/swap
 lvcreate --name root --extents 100%FREE reformvg
 mkfs.ext4 /dev/reformvg/root
 SWAPUUID=$(blkid -s UUID -o value /dev/reformvg/swap)
-CRYPTUUID=$(blkid -s UUID -o value "/dev/$NVMEDEV")
+CRYPTUUID=$(blkid -s UUID -o value "/dev/$DEV_SSD")
 
 echo ""
 printf "The encrypted %s is now set up. Do you want me to run reform-migrate now as well? [y/N] " "$HUMAN"
@@ -100,7 +104,7 @@ if [ "$response" != "y" ]; then
 	echo "echo RESUME=UUID=$SWAPUUID > /etc/initramfs-tools/conf.d/resume"
 	echo "echo reform_crypt UUID=$CRYPTUUID none luks,discard > /etc/crypttab"
 	echo "echo UUID=$SWAPUUID none swap sw 0 0 >> /etc/fstab"
-	echo "cryptsetup luksOpen /dev/$NVMEDEV reform_crypt"
+	echo "cryptsetup luksOpen /dev/$DEV_SSD reform_crypt"
 	echo "vgchange -ay reformvg"
 	echo "reform-migrate /dev/reformvg/root"
 	echo "vgchange -an reformvg"
@@ -119,19 +123,17 @@ else
 	trap "cleanupvg; cleanupluks; error" EXIT INT TERM
 	umount "$ROOTMNT"
 
-	# on A311D, do not attempt writing on eMMC
-	case "$(cat /proc/device-tree/model)" in
-		"MNT Reform 2 with BPI-CM4 Module") reform-boot-config /dev/reformvg/root;;
-		*)
-			printf "Your /boot partition will be on the SD-Card by default. Do you want it on eMMC instead? [y/N] "
-			read -r response
-			if [ "$response" != "y" ]; then
-				reform-boot-config /dev/reformvg/root
-			else
-				reform-boot-config --emmc /dev/reformvg/root
-			fi
-			;;
-	esac
+	if [ "$EMMC_BOOT" = true ]; then
+		printf "Your /boot partition will be on the SD-Card by default. Do you want it on eMMC instead? [y/N] "
+		read -r response
+		if [ "$response" != "y" ]; then
+			reform-boot-config /dev/reformvg/root
+		else
+			reform-boot-config --emmc /dev/reformvg/root
+		fi
+	else
+		reform-boot-config /dev/reformvg/root
+	fi
 fi
 
 trap "cleanupluks; error" EXIT INT TERM
