bin/reform-check: check for /dev/dri/renderD128 and /sys/kernel/debug/devices_deferred

diff --git a/bin/reform-check b/bin/reform-check
--- a/bin/reform-check
+++ b/bin/reform-check
@@ -961,6 +961,44 @@ case "$(cat /proc/device-tree/model)" in "MNT Reform 2" | "MNT Reform 2 HDMI")
   ;;
 esac
 
+if [ ! -e "/dev/dri/renderD128" ]; then
+  echo "E: /dev/dri/renderD128 does not exist -- no hardware accelerated rendering" >&2
+elif [ ! -c "/dev/dri/renderD128" ]; then
+  echo "E: /dev/dri/renderD128 exists but is not a character-special device" >&2
+else
+  if [ "$(stat -c %G /dev/dri/renderD128)" != "render" ]; then
+    echo "W: /dev/dri/renderD128 is not owned by the render group" >&2
+  fi
+  if ! udevadm info --query=property --property=TAGS --value /dev/dri/renderD128 | grep --fixed-strings --quiet ":uaccess:"; then
+    echo "E: udev does not have /dev/dri/renderD128 tagged with 'uaccess' -- non-root user will not have access to hardware rendering" >&2
+  fi
+fi
+
+if ! grep --quiet 'SUBSYSTEM=="drm",.*KERNEL=="renderD.*TAG+="uaccess"' /usr/lib/udev/rules.d/*; then
+  echo "E: missing udev rule to add the 'uaccess' tag to /dev/dri/renderD128" >&2
+fi
+
+if [ -n "${SUDO_USER:-}" ]; then
+  if id --name --groups --zero "$SUDO_USER" \
+    | grep --quiet --null-data --line-regexp --fixed-strings render; then
+    # SUBSYSTEM=="drm", KERNEL=="renderD*", TAG+="uaccess"
+    echo "I: user $SUDO_USER is in the render group which should not be necessary" >&2
+    echo "I: to gain access to /dev/dri/renderD128, use ACLs as they are set by udev's uaccess tag" >&2
+  fi
+  if [ -e "/dev/dri/renderD128" ]; then
+    if ! getfacl --omit-header --absolute-names /dev/dri/renderD128 | grep --line-regexp --fixed-strings --quiet -- "user:$SUDO_USER:rw-"; then
+      echo "E: ACL of /dev/dri/renderD128 does not contain an entry for $SUDO_USER -- missing access means no hardware rendering for non-root users" >&2
+    fi
+  fi
+else
+  echo "I: not executed with sudo -- cannot do tests for the user who ran sudo" >&2
+fi
+
+if test -s /sys/kernel/debug/devices_deferred; then
+  echo "W: /sys/kernel/debug/devices_deferred has the following content:" >&2
+  cat /sys/kernel/debug/devices_deferred >&2
+fi
+
 if [ "$OFFLINE" = "yes" ]; then
   echo "I: skipping the remaining checks because --offline was used" >&2
 else
