bin/reform-check: /boot can be on emmc or sd-card even if u-boot cannot

diff --git a/bin/reform-check b/bin/reform-check
--- a/bin/reform-check
+++ b/bin/reform-check
@@ -396,8 +396,10 @@ fi
 
 if [ -z "$(findmnt --fstab --noheadings --evaluate --mountpoint /boot --output SOURCE)" ]; then
   echo "E: your /etc/fstab does not have an entry for /boot" >&2
-  echo "E: for eMMC booting, add:" >&2
-  echo "/dev/${DEV_MMC}p1 /boot auto errors=remount-ro 0 1" >&2
+  if [ "$EMMC_USE" = true ]; then
+    echo "E: for eMMC booting, add:" >&2
+    echo "/dev/${DEV_MMC}p1 /boot auto errors=remount-ro 0 1" >&2
+  fi
   echo "E: for SD-Card booting, add:" >&2
   echo "/dev/${DEV_SD}p1 /boot auto errors=remount-ro 0 1" >&2
 fi
