bin/reform-check: make the Pocket Reform panel check platform dependent
Link: https://source.mnt.re/reform/reform-tools/-/commit/22ef61a5cb49f9c57e066cea6be7c4694a5835da#note_19414

diff --git a/bin/reform-check b/bin/reform-check
--- a/bin/reform-check
+++ b/bin/reform-check
@@ -317,11 +317,20 @@ case "$MODEL" in
       echo "I: Install ${PKG_REFORM_MCU_TOOL:-reform-tools} and ${PKG_JQ:-jq} to query Pocket controller and keyboard firmware versions" >&2
     fi
 
-    panel_version="$(cat "/sys/devices/platform/fde30000.dsi/fde30000.dsi.0/mnt_pocket_reform_panel_version")"
-    case $panel_version in
-      1 | 2) echo "I: Version of Pocket Reform panel: $panel_version" >&2 ;;
-      *) echo "W: Unknown panel version: $panel_version" >&2 ;;
+    case "$MODEL" in
+      "MNT Pocket Reform with BPI-CM4 Module") panel_version_path="/sys/devices/platform/soc/ffd00000.bus/ffd07000.dsi/ffd07000.dsi.0/mnt_pocket_reform_panel_version" ;;
+      "MNT Pocket Reform with i.MX8MP Module") panel_version_path= ;;
+      "MNT Pocket Reform with RCORE RK3588 Module") panel_version_path="/sys/devices/platform/fde30000.dsi/fde30000.dsi.0/mnt_pocket_reform_panel_version" ;;
+      "MNT Pocket Reform with QUASAR QCS6490 Module") panel_version_path= ;;
     esac
+
+    if [ -z "$panel_version_path" ]; then
+      echo "W: No known path for mnt_pocket_reform_panel_version for $MODEL -- please consider contributing the output of: find /sys -name mnt_pocket_reform_panel_version" >&2
+    elif [ ! -e "$panel_version_path" ]; then
+      echo "W: Unable to read Pocket Reform panel version" >&2
+    else
+      echo "I: Version of Pocket Reform panel: $(cat "$panel_version_path")" >&2
+    fi
     ;;
 esac
 
