bin/reform-check: suggest to remove reform-qcacld2 if not on the i.mx8m+

diff --git a/bin/reform-check b/bin/reform-check
--- a/bin/reform-check
+++ b/bin/reform-check
@@ -552,11 +552,24 @@ if [ "$MIRROR" = "reform.debian.net" ] && dpkg-query --showformat '${db:Status-S
   echo "W: Consider replacing reform-qcacld2 with ezurio-qcacld-2.0-dkms for Debian stable and stable-backports kernels from reform.debian.net" >&2
 fi
 
-if [ "$MIRROR" = "mntre.com" ] && ! dpkg-query --showformat '${db:Status-Status}\n' --show "reform-qcacld2" 2>/dev/null | grep -q '^installed$'; then
-  case "$(cat /proc/device-tree/model)" in "MNT Pocket Reform with i.MX8MP Module.conf")
-    echo "E: For the official MNT Debian on Pocket Reform with i.MX8MP, the reform-qcacld2 package needs to be installed for working wifi" >&2
-    ;;
-  esac
+if [ "$MIRROR" = "mntre.com" ]; then
+  if dpkg-query --showformat '${db:Status-Status}\n' --show "reform-qcacld2" 2>/dev/null | grep -q '^installed$'; then
+    case "$(cat /proc/device-tree/model)" in "MNT Pocket Reform with i.MX8MP Module.conf")
+      :
+      ;; # this is imx8m+, nothing to do
+    *)
+      echo "I: the reform-qcacld2 package package is only required for wifi on the Pocket Reform with i.MX8MP, you can safely remove it unless you plan to go back to the imx8m+" >&2
+      ;;
+    esac
+  else
+    case "$(cat /proc/device-tree/model)" in "MNT Pocket Reform with i.MX8MP Module.conf")
+      echo "E: For the official MNT Debian on Pocket Reform with i.MX8MP, the reform-qcacld2 package needs to be installed for working wifi" >&2
+      ;;
+    *)
+      :
+      ;; # this is not imx8m+, nothing to do
+    esac
+  fi
 fi
 
 if [ ! -e /boot/boot.scr ]; then
