bin/reform-hw-setup: print an error if mdio_mux_meson_g12a is not a module

diff --git a/bin/reform-hw-setup b/bin/reform-hw-setup
--- a/bin/reform-hw-setup
+++ b/bin/reform-hw-setup
@@ -41,13 +41,17 @@ init_a311d() {
   amixer -c 0 sset 'TODDR_A SRC SEL' 'IN 1'
 
   # Workaround for ethernet PHY reset problem
-  for m in dwmac_meson8b dwmac_generic stmmac_platform stmmac mdio_mux_meson_g12a mdio_mux pcs_xpcs mdio_devres of_mdio; do
-    grep --quiet "^$m " /proc/modules || continue
-    rmmod "$m"
-  done
-  sleep 0.5
-  modprobe mdio_mux_meson_g12a
-  modprobe dwmac_meson8b
+  if ! modinfo -n mdio_mux_meson_g12a >/dev/null; then
+    echo "E: modinfo failed for mdio_mux_meson_g12a (not built as a module?) -- unable to reload"
+  else
+    for m in dwmac_meson8b dwmac_generic stmmac_platform stmmac mdio_mux_meson_g12a mdio_mux pcs_xpcs mdio_devres of_mdio; do
+      grep --quiet "^$m " /proc/modules || continue
+      rmmod "$m"
+    done
+    sleep 0.5
+    modprobe mdio_mux_meson_g12a
+    modprobe dwmac_meson8b
+  fi
 
   # Workaround for SDIO wifi not loading
   echo ffe03000.mmc >/sys/class/mmc_host/mmc2/device/driver/unbind
