bin/reform-check: do not fail script if u-boot cannot be downloaded

diff --git a/bin/reform-check b/bin/reform-check
--- a/bin/reform-check
+++ b/bin/reform-check
@@ -156,28 +156,33 @@ fi
 
 ubooturl="https://source.mnt.re/reform/${UBOOT_PROJECT}/-/jobs/artifacts/${UBOOT_TAG}/raw/$(basename "$DTBPATH" .dtb)-flash.bin?job=build"
 ubootbin=$(mktemp)
-/usr/lib/apt/apt-helper download-file "$ubooturl" "$ubootbin" "SHA1:$UBOOT_SHA1" >/dev/null
-if [ ! -e /boot/flash.bin ]; then
-	echo "W: /boot/flash.bin doesn't exist" >&2
-	echo "W: You can download the latest version by running as root:" >&2
-	echo "reform-flash-uboot" >&2
-elif ! cmp --quiet /boot/flash.bin "$ubootbin"; then
-	echo "W: /boot/flash.bin is not the latest uboot" >&2
-	echo "W: You can update it to the latest version by running as root:" >&2
-	echo "reform-flash-uboot" >&2
-fi
-ubootsize=$(stat --format=%s "$ubootbin")
+ret=0
+/usr/lib/apt/apt-helper download-file "$ubooturl" "$ubootbin" "SHA1:$UBOOT_SHA1" >/dev/null || ret=$?
+if [ "$ret" != 0 ]; then
+	echo "E: download of $ubooturl failed" >&2
+else
+	if [ ! -e /boot/flash.bin ]; then
+		echo "W: /boot/flash.bin doesn't exist" >&2
+		echo "W: You can download the latest version by running as root:" >&2
+		echo "reform-flash-uboot" >&2
+	elif ! cmp --quiet /boot/flash.bin "$ubootbin"; then
+		echo "W: /boot/flash.bin is not the latest uboot" >&2
+		echo "W: You can update it to the latest version by running as root:" >&2
+		echo "reform-flash-uboot" >&2
+	fi
+	ubootsize=$(stat --format=%s "$ubootbin")
 
-if [ "$EMMC_BOOT" = true ] && ! cmp --quiet --bytes="$ubootsize" "--ignore-initial=$FLASHBIN_OFFSET:$UBOOT_OFFSET" "$ubootbin" "/dev/${DEV_MMC}boot0" 2>/dev/null; then
-	echo "W: eMMC does not contain latest uboot" >&2
-	echo "W: You can update it to the latest version by running as root:" >&2
-	echo "reform-flash-uboot emmc" >&2
-fi
+	if [ "$EMMC_BOOT" = true ] && ! cmp --quiet --bytes="$ubootsize" "--ignore-initial=$FLASHBIN_OFFSET:$UBOOT_OFFSET" "$ubootbin" "/dev/${DEV_MMC}boot0" 2>/dev/null; then
+		echo "W: eMMC does not contain latest uboot" >&2
+		echo "W: You can update it to the latest version by running as root:" >&2
+		echo "reform-flash-uboot emmc" >&2
+	fi
 
-if [ "$SD_BOOT" = true ] && [ -e "/dev/$DEV_SD" ] && ! cmp --quiet --bytes="$ubootsize" --ignore-initial="0:$UBOOT_OFFSET" "$ubootbin" "/dev/$DEV_SD" 2>/dev/null; then
-	echo "W: SD-Card does not contain latest uboot" >&2
-	echo "W: You can update it to the latest version by running as root:" >&2
-	echo "reform-flash-uboot sd" >&2
+	if [ "$SD_BOOT" = true ] && [ -e "/dev/$DEV_SD" ] && ! cmp --quiet --bytes="$ubootsize" --ignore-initial="0:$UBOOT_OFFSET" "$ubootbin" "/dev/$DEV_SD" 2>/dev/null; then
+		echo "W: SD-Card does not contain latest uboot" >&2
+		echo "W: You can update it to the latest version by running as root:" >&2
+		echo "reform-flash-uboot sd" >&2
+	fi
 fi
 rm "$ubootbin"
 
