bin/reform-flash-rescue: add --mirror argument

diff --git a/bin/reform-flash-rescue b/bin/reform-flash-rescue
--- a/bin/reform-flash-rescue
+++ b/bin/reform-flash-rescue
@@ -11,15 +11,33 @@ usage() {
   echo "filesystem and adjusts filesystem labels." >&2
   echo "Calls reform-boot-config to set up /boot on eMMC to load the rootfs from eMMC." >&2
   echo >&2
-  echo "Usage: $0 [--help]" >&2
+  echo "Usage: $0 [--help] [--mirror={mntre.com,reform.debian.net}]" >&2
   echo >&2
   echo "Options:" >&2
   echo "  --help           Display this help and exit." >&2
+  echo "  --mirror=MIRROR  Force MIRROR, either mntre.com (default) or reform.debian.net" >&2
 }
+
+if [ "$#" -gt 1 ]; then
+  echo "E: incorrect number of arguments" >&2
+  exit 1
+fi
 
 if [ "$#" -gt 0 ] && [ "$1" = "--help" ]; then
   usage
   exit 0
+fi
+
+MIRROR="mntre.com"
+if [ "$#" -gt 0 ]; then
+  case $1 in
+    --mirror=mntre.com) MIRROR="mntre.com" ;;
+    --mirror=reform.debian.net) MIRROR="reform.debian.net" ;;
+    *)
+      echo "E: invalid argument for --mirror" >&2
+      exit 1
+      ;;
+  esac
 fi
 
 # shellcheck source=/dev/null
@@ -119,23 +137,31 @@ if [ "$response" != "y" ]; then
   exit
 fi
 
-URL="https://source.mnt.re/reform/reform-system-image/-/jobs/artifacts/main/raw/${SYSIMAGE}.img.gz?job=build"
-DECOMPRESSOR=gzip
+if [ "$MIRROR" = "mntre.com" ]; then
+  URL="https://source.mnt.re/reform/reform-system-image/-/jobs/artifacts/main/raw/${SYSIMAGE}.img.gz?job=build"
+  DECOMPRESSOR=gzip
 
-if grep --silent '^URIs: https://reform.debian.net/debian/\?$' /etc/apt/sources.list.d/reform*.sources 2>/dev/null; then
-  echo "The current system image is configured to use the Debian stable mirror from" >&2
-  echo "reform.debian.net. Do you want to flash the system image from reform.debian.net" >&2
-  echo 'to your eMMC? If you answer anything but "y", the official MNT system image will' >&2
-  echo "be downloaded and written to eMMC instead." >&2
-  printf "Do you want to download and use the rescue system image from reform.debian.net? [y/N] "
+  if grep --silent '^URIs: https://reform.debian.net/debian/\?$' /etc/apt/sources.list.d/reform*.sources 2>/dev/null; then
+    echo "The current system image is configured to use the Debian stable mirror from" >&2
+    echo "reform.debian.net. Do you want to flash the system image from reform.debian.net" >&2
+    echo 'to your eMMC? If you answer anything but "y", the official MNT system image will' >&2
+    echo "be downloaded and written to eMMC instead." >&2
+    printf "Do you want to download and use the rescue system image from reform.debian.net? [y/N] "
 
-  read -r response
-  if [ "$response" = "y" ]; then
-    # no need to use the backports kernel because a311d is not
-    # allowed to write to emmc anyways
-    URL="https://reform.debian.net/images/${SYSIMAGE}.img.xz"
-    DECOMPRESSOR=xz
+    read -r response
+    if [ "$response" = "y" ]; then
+      # no need to use the backports kernel because a311d is not
+      # allowed to write to emmc anyways
+      URL="https://reform.debian.net/images/${SYSIMAGE}.img.xz"
+      DECOMPRESSOR=xz
+    fi
   fi
+elif [ "$MIRROR" = "reform.debian.net" ]; then
+  URL="https://reform.debian.net/images/${SYSIMAGE}.img.xz"
+  DECOMPRESSOR=xz
+else
+  echo "E: unsupported value for --mirror: $MIRROR" >&2
+  exit 1
 fi
 
 echo "Downloading $URL..."
