bin/reform-check: fix error message

diff --git a/bin/reform-check b/bin/reform-check
--- a/bin/reform-check
+++ b/bin/reform-check
@@ -66,7 +66,7 @@ while getopts :h-: OPTCHAR; do
         offline) OFFLINE=yes ;;
         mirror)
           if [ "$OPTIND" -gt "$#" ]; then
-            echo "E: missing argument for --image" >&2
+            echo "E: missing argument for --mirror" >&2
             exit 1
           fi
           MIRROR="$(nth_arg "$OPTIND" "$@")"
