reformat shell with shfmt --posix --simplify --binary-next-line --case-indent --indent 2
This is similar to Google's shell style defined in
https://google.github.io/styleguide/shellguide.html

diff --git a/initramfs-tools/hooks/reform b/initramfs-tools/hooks/reform
--- a/initramfs-tools/hooks/reform
+++ b/initramfs-tools/hooks/reform
@@ -4,47 +4,51 @@ set -e
 
 PREREQ=""
 prereqs() { echo "$PREREQ"; }
-case $1 in prereqs) prereqs; exit 0 ;; esac
+case $1 in prereqs)
+  prereqs
+  exit 0
+  ;;
+esac
 
 . /usr/share/initramfs-tools/hook-functions
 
 MACHINE=
 if [ -e /etc/flash-kernel/machine ]; then
-	MACHINE=$(cat /etc/flash-kernel/machine)
+  MACHINE=$(cat /etc/flash-kernel/machine)
 elif [ -e /proc/device-tree/model ]; then
-	MACHINE=$(cat /proc/device-tree/model)
+  MACHINE=$(cat /proc/device-tree/model)
 fi
 
 copy_reform_font() {
-		copy_exec /usr/bin/setfont
-		copy_file Uni2-TerminusBold32x16 /usr/share/consolefonts/Uni2-TerminusBold32x16.psf.gz
-	}
+  copy_exec /usr/bin/setfont
+  copy_file Uni2-TerminusBold32x16 /usr/share/consolefonts/Uni2-TerminusBold32x16.psf.gz
+}
 
 case $MACHINE in
-	"MNT Reform 2") : ;;
-	"MNT Reform 2 HDMI") : ;;
-	"MNT Reform 2 with BPI-CM4 Module") : ;;
-	"MNT Reform 2 with LS1028A Module")
-		[ "${verbose}" = "y" ] && echo "Adding firmware ls1028a-mhdpfw.bin"
-		copy_file firmware /boot/ls1028a-mhdpfw.bin /lib/firmware
-		[ "${verbose}" = "y" ] && echo "Adding /usr/bin/dmesg"
-		copy_exec /usr/bin/dmesg
-		;;
-	"MNT Reform 2 with RCORE RK3588 Module") : ;;
-	"MNT Pocket Reform with i.MX8MP Module")
-		copy_reform_font
-		;;
-	"MNT Pocket Reform with BPI-CM4 Module")
-		copy_reform_font
-		;;
-	"MNT Pocket Reform with RCORE RK3588 Module")
-		copy_reform_font
-		;;
-	"MNT Reform Next with RCORE RK3588 Module") : ;;
-	"")
-		echo "W: unable to deduce target machine for reform initramfs-hook" >&2
-		;;
-	*)
-		echo "W: unsupported machine: $MACHINE" >&2
-		;;
+  "MNT Reform 2") : ;;
+  "MNT Reform 2 HDMI") : ;;
+  "MNT Reform 2 with BPI-CM4 Module") : ;;
+  "MNT Reform 2 with LS1028A Module")
+    [ "${verbose}" = "y" ] && echo "Adding firmware ls1028a-mhdpfw.bin"
+    copy_file firmware /boot/ls1028a-mhdpfw.bin /lib/firmware
+    [ "${verbose}" = "y" ] && echo "Adding /usr/bin/dmesg"
+    copy_exec /usr/bin/dmesg
+    ;;
+  "MNT Reform 2 with RCORE RK3588 Module") : ;;
+  "MNT Pocket Reform with i.MX8MP Module")
+    copy_reform_font
+    ;;
+  "MNT Pocket Reform with BPI-CM4 Module")
+    copy_reform_font
+    ;;
+  "MNT Pocket Reform with RCORE RK3588 Module")
+    copy_reform_font
+    ;;
+  "MNT Reform Next with RCORE RK3588 Module") : ;;
+  "")
+    echo "W: unable to deduce target machine for reform initramfs-hook" >&2
+    ;;
+  *)
+    echo "W: unsupported machine: $MACHINE" >&2
+    ;;
 esac
diff --git a/initramfs-tools/scripts/reform b/initramfs-tools/scripts/reform
--- a/initramfs-tools/scripts/reform
+++ b/initramfs-tools/scripts/reform
@@ -1,24 +1,24 @@
 #!/bin/sh
 
-case $1 in prereqs) exit 0;; esac
+case $1 in prereqs) exit 0 ;; esac
 
 . /scripts/functions
 
 MACHINE=
 if [ -e /etc/flash-kernel/machine ]; then
-	MACHINE=$(cat /etc/flash-kernel/machine)
+  MACHINE=$(cat /etc/flash-kernel/machine)
 elif [ -e /proc/device-tree/model ]; then
-	MACHINE=$(cat /proc/device-tree/model)
+  MACHINE=$(cat /proc/device-tree/model)
 fi
 
 case $MACHINE in
-	"MNT Reform 2 with LS1028A Module")
-		# https://source.mnt.re/reform/reform-debian-packages/-/issues/5
-		dmesg -n 7 || echo "E: failed to set kernel loglevel" >&2
-		;;
-	"MNT Pocket Reform"*)
-		for c in 1 2 3 4 5 6 7
-			do setfont -C /dev/tty$c Uni2-TerminusBold32x16
-		done
-		;;
+  "MNT Reform 2 with LS1028A Module")
+    # https://source.mnt.re/reform/reform-debian-packages/-/issues/5
+    dmesg -n 7 || echo "E: failed to set kernel loglevel" >&2
+    ;;
+  "MNT Pocket Reform"*)
+    for c in 1 2 3 4 5 6 7; do
+      setfont -C /dev/tty$c Uni2-TerminusBold32x16
+    done
+    ;;
 esac
diff --git a/sbin/reform-flash-uboot b/sbin/reform-flash-uboot
--- a/sbin/reform-flash-uboot
+++ b/sbin/reform-flash-uboot
@@ -2,201 +2,203 @@
 
 set -eu
 
-usage () {
-	echo "Download latest u-boot for the current platform and update /boot/flash.bin">&2
-	echo "Then flash u-boot to DEVICE which can be one of the short-hands sd or emmc.">&2
-	echo >&2
-	echo "Usage: $0 [--help] [--offline] DEVICE" >&2
-	echo >&2
-	echo "Options:" >&2
-	echo "  DEVICE           Either a device path in /dev or shorthands sd and emmc" >&2
-	echo "  --help           Display this help and exit." >&2
-	echo "  --offline        Instead of download u-boot use /boot/flash.bin." >&2
+usage() {
+  echo "Download latest u-boot for the current platform and update /boot/flash.bin" >&2
+  echo "Then flash u-boot to DEVICE which can be one of the short-hands sd or emmc." >&2
+  echo >&2
+  echo "Usage: $0 [--help] [--offline] DEVICE" >&2
+  echo >&2
+  echo "Options:" >&2
+  echo "  DEVICE           Either a device path in /dev or shorthands sd and emmc" >&2
+  echo "  --help           Display this help and exit." >&2
+  echo "  --offline        Instead of download u-boot use /boot/flash.bin." >&2
 }
 
 if [ "$#" -gt 0 ] && [ "$1" = "--help" ]; then
-	usage
-	exit 0
+  usage
+  exit 0
 fi
 
 # shellcheck source=/dev/null
 if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
-	. "./machines/$(cat /proc/device-tree/model).conf"
+  . "./machines/$(cat /proc/device-tree/model).conf"
 elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
-	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+  . "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
 else
-	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
-	exit 1
+  echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+  exit 1
 fi
 
 if [ "$EMMC_BOOT" = false ]; then
-	for dev in "$@"; do
-		case $dev in emmc|"/dev/${DEV_MMC}"*)
-			echo "E: writing uboot to eMMC not supported on $(cat /proc/device-tree/model)" >&2
-			exit 1
-			;;
-		esac
-	done
+  for dev in "$@"; do
+    case $dev in emmc | "/dev/${DEV_MMC}"*)
+      echo "E: writing uboot to eMMC not supported on $(cat /proc/device-tree/model)" >&2
+      exit 1
+      ;;
+    esac
+  done
 fi
 if [ "$SD_BOOT" = false ]; then
-	for dev in "$@"; do
-		case $dev in sd|"/dev/${DEV_SD}"*)
-			echo "E: writing uboot to SD-Card not supported on $(cat /proc/device-tree/model)" >&2
-			exit 1
-			;;
-		esac
-	done
+  for dev in "$@"; do
+    case $dev in sd | "/dev/${DEV_SD}"*)
+      echo "E: writing uboot to SD-Card not supported on $(cat /proc/device-tree/model)" >&2
+      exit 1
+      ;;
+    esac
+  done
 fi
 
 usage() {
-	echo "Usage: " >&2
-	echo "  reform-flash-uboot [--offline] [device...]" >&2
-	echo "" >&2
-	if [ "$EMMC_BOOT" = true ] && [ "$SD_BOOT" = true ]; then
-		echo "Download and write recent uboot to eMMC or SD-Card." >&2
-	elif [ "$SD_BOOT" = true ]; then
-		echo "Download and write recent uboot to SD-Card." >&2
-	elif [ "$EMMC_BOOT" = true ]; then
-		echo "Download and write recent uboot to eMMC." >&2
-	else
-		echo "Download and write recent uboot to chosen device." >&2
-	fi
-	echo "Without arguments only /boot/flash.bin will be updated unless --offline is given." >&2
-	echo "Otherwise, the arguments are the devices onto which to install uboot." >&2
-	if [ "$EMMC_BOOT" = true ] && [ "$SD_BOOT" = true ]; then
-		echo "Two device shortcuts are provided:" >&2
-		echo "" >&2
-		echo "   emmc -> /dev/${DEV_MMC}boot0" >&2
-		echo "   sd -> /dev/${DEV_SD}" >&2
-		echo "" >&2
-	elif [ "$SD_BOOT" = true ]; then
-		echo "A device shortcut is provided:" >&2
-		echo "" >&2
-		echo "   sd -> /dev/${DEV_SD}" >&2
-		echo "" >&2
-	elif [ "$EMMC_BOOT" = true ]; then
-		echo "A device shortcut is provided:" >&2
-		echo "" >&2
-		echo "   emmc -> /dev/${DEV_MMC}boot0" >&2
-		echo "" >&2
-	fi
+  echo "Usage: " >&2
+  echo "  reform-flash-uboot [--offline] [device...]" >&2
+  echo "" >&2
+  if [ "$EMMC_BOOT" = true ] && [ "$SD_BOOT" = true ]; then
+    echo "Download and write recent uboot to eMMC or SD-Card." >&2
+  elif [ "$SD_BOOT" = true ]; then
+    echo "Download and write recent uboot to SD-Card." >&2
+  elif [ "$EMMC_BOOT" = true ]; then
+    echo "Download and write recent uboot to eMMC." >&2
+  else
+    echo "Download and write recent uboot to chosen device." >&2
+  fi
+  echo "Without arguments only /boot/flash.bin will be updated unless --offline is given." >&2
+  echo "Otherwise, the arguments are the devices onto which to install uboot." >&2
+  if [ "$EMMC_BOOT" = true ] && [ "$SD_BOOT" = true ]; then
+    echo "Two device shortcuts are provided:" >&2
+    echo "" >&2
+    echo "   emmc -> /dev/${DEV_MMC}boot0" >&2
+    echo "   sd -> /dev/${DEV_SD}" >&2
+    echo "" >&2
+  elif [ "$SD_BOOT" = true ]; then
+    echo "A device shortcut is provided:" >&2
+    echo "" >&2
+    echo "   sd -> /dev/${DEV_SD}" >&2
+    echo "" >&2
+  elif [ "$EMMC_BOOT" = true ]; then
+    echo "A device shortcut is provided:" >&2
+    echo "" >&2
+    echo "   emmc -> /dev/${DEV_MMC}boot0" >&2
+    echo "" >&2
+  fi
 }
 
 if [ "$#" -gt 0 ] && [ "$1" = "--help" ] || [ "$#" -gt 0 ] && [ "$1" = "-h" ]; then
-	usage
-	exit 0
+  usage
+  exit 0
 fi
 
 if [ "$(id -u)" -ne 0 ]; then
-	echo "reform-flash-uboot has to be run as root / using sudo."
-	exit 1
+  echo "reform-flash-uboot has to be run as root / using sudo."
+  exit 1
 fi
 
 if [ "$#" -eq 0 ] || [ "$1" != "--offline" ]; then
-	echo "Downloading uboot to /boot/flash.bin and comparing checksum" >&2
+  echo "Downloading uboot to /boot/flash.bin and comparing checksum" >&2
 
-	ubooturl="https://source.mnt.re/reform/${UBOOT_PROJECT}/-/jobs/artifacts/${UBOOT_TAG}/raw/$(basename "$DTBPATH" .dtb)-flash.bin?job=build"
-	/usr/lib/apt/apt-helper -oAPT::Sandbox::User=root download-file "$ubooturl" "/boot/flash.bin" "SHA1:$UBOOT_SHA1"
-	# download mhdpfw.bin on ls1028a
-	case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with LS1028A Module")
-		/usr/lib/apt/apt-helper -oAPT::Sandbox::User=root download-file \
-			"https://source.mnt.re/reform/reform-ls1028a-uboot/-/raw/main/ls1028a-mhdpfw.bin" \
-			"/boot/ls1028a-mhdpfw.bin" \
-			"SHA1:fa96b9aa59d7c1e9e6ee1c0375d0bcc8f8e5b78c"
-		;;
-	esac
+  ubooturl="https://source.mnt.re/reform/${UBOOT_PROJECT}/-/jobs/artifacts/${UBOOT_TAG}/raw/$(basename "$DTBPATH" .dtb)-flash.bin?job=build"
+  /usr/lib/apt/apt-helper -oAPT::Sandbox::User=root download-file "$ubooturl" "/boot/flash.bin" "SHA1:$UBOOT_SHA1"
+  # download mhdpfw.bin on ls1028a
+  case "$(cat /proc/device-tree/model)" in "MNT Reform 2 with LS1028A Module")
+    /usr/lib/apt/apt-helper -oAPT::Sandbox::User=root download-file \
+      "https://source.mnt.re/reform/reform-ls1028a-uboot/-/raw/main/ls1028a-mhdpfw.bin" \
+      "/boot/ls1028a-mhdpfw.bin" \
+      "SHA1:fa96b9aa59d7c1e9e6ee1c0375d0bcc8f8e5b78c"
+    ;;
+  esac
 elif [ "$#" -gt 0 ] && [ "$1" = "--offline" ]; then
-	echo "Not downloading uboot but using /boot/flash.bin without updating it." >&2
-	shift
-	if ! echo "$UBOOT_SHA1  /boot/flash.bin" | sha1sum --strict --check >/dev/null 2>&1; then
-		echo "Incorrect checksum for /boot/flash.bin" >&2
-		echo "Either flash manually, or run without --offline to download the latest uboot version" >&2
-		exit 1
-	fi
+  echo "Not downloading uboot but using /boot/flash.bin without updating it." >&2
+  shift
+  if ! echo "$UBOOT_SHA1  /boot/flash.bin" | sha1sum --strict --check >/dev/null 2>&1; then
+    echo "Incorrect checksum for /boot/flash.bin" >&2
+    echo "Either flash manually, or run without --offline to download the latest uboot version" >&2
+    exit 1
+  fi
 fi
 
 if [ "$#" -eq 0 ]; then
-	echo "No device unto which to flash uboot provided. Exiting." >&2
-	exit 0
+  echo "No device unto which to flash uboot provided. Exiting." >&2
+  exit 0
 fi
 
 ubootsize=$(stat --format=%s "/boot/flash.bin")
 
 # check if there is enough free space at the beginning of the disk
 for dev in "$@"; do
-	case $dev in
-		emmc) dev=/dev/${DEV_MMC}boot0;;
-		sd)   dev=/dev/${DEV_SD};;
-	esac
+  case $dev in
+    emmc) dev=/dev/${DEV_MMC}boot0 ;;
+    sd) dev=/dev/${DEV_SD} ;;
+  esac
 
-	if [ "$dev" = "/dev/${DEV_MMC}boot0" ]; then
-		continue
-	fi
+  if [ "$dev" = "/dev/${DEV_MMC}boot0" ]; then
+    continue
+  fi
 
-	# no further tests for disks without a partition table
-	if [ "$(parted --script --machine "$dev" unit B print 2>/dev/null | grep "^$dev:" | cut -d: -f 6)" = unknown ]; then
-		continue
-	fi
+  # no further tests for disks without a partition table
+  if [ "$(parted --script --machine "$dev" unit B print 2>/dev/null | grep "^$dev:" | cut -d: -f 6)" = unknown ]; then
+    continue
+  fi
 
-	freeuntil=$(parted --script --machine "$dev" unit B print free | grep --max-count=1 '^1:1024B:.*:free;')
-	freeuntil=${freeuntil##1:1024B:}
-	freeuntil=${freeuntil%B:*:free;}
-	# The following checks whether the parsed output is a valid integer.
-	# We cannot use [0-9] because that matches on any character (or
-	# possibly multi-character collation element) that sorts in between 0
-	# and 9.
-	# https://lists.gnu.org/archive/html/bug-bash/2021-02/msg00054.html
-	case "$freeuntil" in *[!0123456789]*|0?*|"")
-		echo "Unexpected parted output";
-		exit 1
-	esac
+  freeuntil=$(parted --script --machine "$dev" unit B print free | grep --max-count=1 '^1:1024B:.*:free;')
+  freeuntil=${freeuntil##1:1024B:}
+  freeuntil=${freeuntil%B:*:free;}
+  # The following checks whether the parsed output is a valid integer.
+  # We cannot use [0-9] because that matches on any character (or
+  # possibly multi-character collation element) that sorts in between 0
+  # and 9.
+  # https://lists.gnu.org/archive/html/bug-bash/2021-02/msg00054.html
+  case "$freeuntil" in *[!0123456789]* | 0?* | "")
+    echo "Unexpected parted output"
+    exit 1
+    ;;
+  esac
 
-	if [ "$((UBOOT_OFFSET-FLASHBIN_OFFSET+ubootsize))" -ge "$freeuntil" ]; then
-		echo "the first partition on $dev starts at $freeuntil and would be overwritten by uboot" >&2
-		echo "make sure that the first $((UBOOT_OFFSET-FLASHBIN_OFFSET+ubootsize)) bytes are free on $dev" >&2
-		exit 1
-	fi
+  if [ "$((UBOOT_OFFSET - FLASHBIN_OFFSET + ubootsize))" -ge "$freeuntil" ]; then
+    echo "the first partition on $dev starts at $freeuntil and would be overwritten by uboot" >&2
+    echo "make sure that the first $((UBOOT_OFFSET - FLASHBIN_OFFSET + ubootsize)) bytes are free on $dev" >&2
+    exit 1
+  fi
 done
 
 # do the flashing
 for dev in "$@"; do
-	case $dev in
-		emmc) dev=/dev/${DEV_MMC}boot0;;
-		sd)   dev=/dev/${DEV_SD};;
-	esac
+  case $dev in
+    emmc) dev=/dev/${DEV_MMC}boot0 ;;
+    sd) dev=/dev/${DEV_SD} ;;
+  esac
 
-	echo "Writing /boot/flash.bin to $dev" >&2
+  echo "Writing /boot/flash.bin to $dev" >&2
 
-	if [ "$dev" = "/dev/${DEV_MMC}boot0" ]; then
-		echo 0 > "/sys/class/block/${DEV_MMC}boot0/force_ro"
-		dd if=/boot/flash.bin of="/dev/${DEV_MMC}boot0" bs=512 seek="$((UBOOT_OFFSET/512))" skip="$((FLASHBIN_OFFSET/512))"
-		echo 1 > "/sys/class/block/${DEV_MMC}boot0/force_ro"
-		continue
-	fi
+  if [ "$dev" = "/dev/${DEV_MMC}boot0" ]; then
+    echo 0 >"/sys/class/block/${DEV_MMC}boot0/force_ro"
+    dd if=/boot/flash.bin of="/dev/${DEV_MMC}boot0" bs=512 seek="$((UBOOT_OFFSET / 512))" skip="$((FLASHBIN_OFFSET / 512))"
+    echo 1 >"/sys/class/block/${DEV_MMC}boot0/force_ro"
+    continue
+  fi
 
-	dd if=/boot/flash.bin of="$dev" bs=512 seek="$((UBOOT_OFFSET/512))" skip="$((FLASHBIN_OFFSET/512))"
+  dd if=/boot/flash.bin of="$dev" bs=512 seek="$((UBOOT_OFFSET / 512))" skip="$((FLASHBIN_OFFSET / 512))"
 done
 
 # inform about the DIP switch position only on imx8mq
-case "$(cat /proc/device-tree/model)" in "MNT Reform 2"|"MNT Reform 2 HDMI")
-	DOMMC=0
-	DOSD=0
-	for dev in "$@"; do
-		case $dev in
-			emmc) dev=/dev/${DEV_MMC}boot0;;
-			sd)   dev=/dev/${DEV_SD};;
-		esac
-		case $dev in
-			"/dev/${DEV_MMC}"*) DOMMC=1;;
-			"/dev/${DEV_SD}"*)  DOSD=1;;
-		esac
-	done
-	if [ "$DOMMC" != "0" ]; then
-		echo "For the i.MX8MQ to load u-boot from MMC, make sure" >&2
-		echo "that your DIP switch is set to OFF." >&2
-	fi
-	if [ "$DOSD" != "0" ]; then
-		echo "For the i.MX8MQ to load u-boot from SD-Card, make sure" >&2
-		echo "that your DIP switch is set to ON." >&2
-	fi
+case "$(cat /proc/device-tree/model)" in "MNT Reform 2" | "MNT Reform 2 HDMI")
+  DOMMC=0
+  DOSD=0
+  for dev in "$@"; do
+    case $dev in
+      emmc) dev=/dev/${DEV_MMC}boot0 ;;
+      sd) dev=/dev/${DEV_SD} ;;
+    esac
+    case $dev in
+      "/dev/${DEV_MMC}"*) DOMMC=1 ;;
+      "/dev/${DEV_SD}"*) DOSD=1 ;;
+    esac
+  done
+  if [ "$DOMMC" != "0" ]; then
+    echo "For the i.MX8MQ to load u-boot from MMC, make sure" >&2
+    echo "that your DIP switch is set to OFF." >&2
+  fi
+  if [ "$DOSD" != "0" ]; then
+    echo "For the i.MX8MQ to load u-boot from SD-Card, make sure" >&2
+    echo "that your DIP switch is set to ON." >&2
+  fi
+  ;;
 esac
diff --git a/sbin/reform-hw-setup b/sbin/reform-hw-setup
--- a/sbin/reform-hw-setup
+++ b/sbin/reform-hw-setup
@@ -2,125 +2,125 @@
 
 set -eu
 
-usage () {
-	echo "Hardware setup specific to your MNT Reform platform." >&2
-	echo "Usually run by /lib/systemd/system/reform-hw-setup.service" >&2
-	echo >&2
-	echo "Usage: $0 [--help]" >&2
-	echo >&2
-	echo "Options:" >&2
-	echo "  --help           Display this help and exit." >&2
+usage() {
+  echo "Hardware setup specific to your MNT Reform platform." >&2
+  echo "Usually run by /lib/systemd/system/reform-hw-setup.service" >&2
+  echo >&2
+  echo "Usage: $0 [--help]" >&2
+  echo >&2
+  echo "Options:" >&2
+  echo "  --help           Display this help and exit." >&2
 }
 
 if [ "$#" -gt 0 ]; then
-	if [ "$1" != "--help" ]; then
-		echo "E: too many arguments" >&2
-		usage
-		exit 1
-	fi
-	usage
-	exit 0
+  if [ "$1" != "--help" ]; then
+    echo "E: too many arguments" >&2
+    usage
+    exit 1
+  fi
+  usage
+  exit 0
 fi
 
 init_a311d() {
-    # A311D sound controls
-    # without setting these, there is no UCM profile and messages like this are produced:
-    # no backend DAIs enabled for fe.dai-link-0, possibly missing ALSA mixer-based routing or UCM profile
-    amixer -c 0 sset 'FRDDR_A SINK 1 SEL' 'OUT 1'
-    amixer -c 0 sset 'FRDDR_A SRC 1 EN' 'on'
-    amixer -c 0 sset 'TDMOUT_B SRC SEL' 'IN 0'
-    amixer -c 0 sset 'TDMIN_B SRC SEL' 'IN 1'
-    amixer -c 0 sset 'TODDR_A SRC SEL' 'IN 1'
+  # A311D sound controls
+  # without setting these, there is no UCM profile and messages like this are produced:
+  # no backend DAIs enabled for fe.dai-link-0, possibly missing ALSA mixer-based routing or UCM profile
+  amixer -c 0 sset 'FRDDR_A SINK 1 SEL' 'OUT 1'
+  amixer -c 0 sset 'FRDDR_A SRC 1 EN' 'on'
+  amixer -c 0 sset 'TDMOUT_B SRC SEL' 'IN 0'
+  amixer -c 0 sset 'TDMIN_B SRC SEL' 'IN 1'
+  amixer -c 0 sset 'TODDR_A SRC SEL' 'IN 1'
 
-    # Workaround for ethernet PHY reset problem
-    for m in dwmac_meson8b dwmac_generic stmmac_platform stmmac mdio_mux_meson_g12a mdio_mux pcs_xpcs mdio_devres of_mdio; do
-      grep --quiet "^$m " /proc/modules || continue;
-      rmmod "$m"
-    done
-    sleep 0.5
-    modprobe mdio_mux_meson_g12a
-    modprobe dwmac_meson8b
+  # Workaround for ethernet PHY reset problem
+  for m in dwmac_meson8b dwmac_generic stmmac_platform stmmac mdio_mux_meson_g12a mdio_mux pcs_xpcs mdio_devres of_mdio; do
+    grep --quiet "^$m " /proc/modules || continue
+    rmmod "$m"
+  done
+  sleep 0.5
+  modprobe mdio_mux_meson_g12a
+  modprobe dwmac_meson8b
 
-    # Workaround for SDIO wifi not loading
-    echo ffe03000.mmc > /sys/class/mmc_host/mmc2/device/driver/unbind
-    echo ffe03000.mmc > /sys/bus/platform/drivers/meson-gx-mmc/bind
+  # Workaround for SDIO wifi not loading
+  echo ffe03000.mmc >/sys/class/mmc_host/mmc2/device/driver/unbind
+  echo ffe03000.mmc >/sys/bus/platform/drivers/meson-gx-mmc/bind
 }
 
 init_wm8960() {
-    # Fix WM8960 being too quiet
-    amixer -c 0 sset Playback 255
-    amixer -c 0 sset 'Left Output Mixer PCM' on
-    amixer -c 0 sset 'Right Output Mixer PCM' on
-    # This switch in WM8960 needs to be on for the headset mic input to work
-    amixer -c 0 sset 'Left Input Mixer Boost' on
+  # Fix WM8960 being too quiet
+  amixer -c 0 sset Playback 255
+  amixer -c 0 sset 'Left Output Mixer PCM' on
+  amixer -c 0 sset 'Right Output Mixer PCM' on
+  # This switch in WM8960 needs to be on for the headset mic input to work
+  amixer -c 0 sset 'Left Input Mixer Boost' on
 }
 
 init_tlv320aic3100() {
-    # Set up speaker on MNT Pocket Reform
-    amixer -c 0 sset 'Speaker Driver' on
-    amixer -c 0 sset 'Output Left From Left DAC' on
-    amixer -c 0 sset 'Output Right From Right DAC' on
-    amixer -c 0 sset 'Speaker Analog' 127
-    amixer -c 0 sset 'DAC' 127
-    amixer -c 0 sset 'HP Analog' 127
-    amixer -c 0 sset 'HP Driver' on
-    amixer -c 0 sset 'HP Left' on
-    amixer -c 0 sset 'HP Right' on
+  # Set up speaker on MNT Pocket Reform
+  amixer -c 0 sset 'Speaker Driver' on
+  amixer -c 0 sset 'Output Left From Left DAC' on
+  amixer -c 0 sset 'Output Right From Right DAC' on
+  amixer -c 0 sset 'Speaker Analog' 127
+  amixer -c 0 sset 'DAC' 127
+  amixer -c 0 sset 'HP Analog' 127
+  amixer -c 0 sset 'HP Driver' on
+  amixer -c 0 sset 'HP Left' on
+  amixer -c 0 sset 'HP Right' on
 }
 
 init_pocket_display() {
-    # Increase console font size (MNT Pocket Reform has a Hi-DPI display)
-    for c in 1 2 3 4 5 6 7
-        do setfont -C /dev/tty$c /usr/share/consolefonts/Uni2-TerminusBold32x16.psf.gz
-    done
+  # Increase console font size (MNT Pocket Reform has a Hi-DPI display)
+  for c in 1 2 3 4 5 6 7; do
+    setfont -C /dev/tty$c /usr/share/consolefonts/Uni2-TerminusBold32x16.psf.gz
+  done
 }
 
 init_qca9377_wifi() {
-    if test -e /proc/modules && grep --quiet '^qcacld2 ' /proc/modules; then
-        echo "I: Module qcacld2 is already loaded" >&2
-        return 0
+  if test -e /proc/modules && grep --quiet '^qcacld2 ' /proc/modules; then
+    echo "I: Module qcacld2 is already loaded" >&2
+    return 0
+  fi
+
+  # load out-of-tree Wi-Fi driver
+  KERNVER_EXACT=$(dpkg-query --show --showformat '${Version}' "linux-image-$(uname -r)")
+  modprobe cfg80211
+
+  # without "-f", insmod will fail with "Invalid module format" even though
+  # the kernel version matches
+  echo "I: Try to load exact match wifi driver: ${KERNVER_EXACT}" >&2
+  if [ -f "/opt/reform-qcacld2/qcacld2-${KERNVER_EXACT}.ko" ]; then
+    echo "I: Found exact match for kernel ${KERNVER_EXACT}" >&2
+    if insmod -f "/opt/reform-qcacld2/qcacld2-${KERNVER_EXACT}.ko"; then
+      echo "I: Successfully loaded exact match driver" >&2
+      return 0
+    else
+      echo "W: Failed to load exact match driver. Try other available driver" >&2
     fi
+  fi
 
-    # load out-of-tree Wi-Fi driver
-    KERNVER_EXACT=$(dpkg-query --show --showformat '${Version}' "linux-image-$(uname -r)")
-    modprobe cfg80211
+  # Find other potential qcacld2 drivers
+  potential_drivers=$(find /opt/reform-qcacld2/qcacld2-*.ko -maxdepth 1 -type f -print0 | sort -Vzr)
 
-    # without "-f", insmod will fail with "Invalid module format" even though
-    # the kernel version matches
-    echo "I: Try to load exact match wifi driver: ${KERNVER_EXACT}" >&2
-    if [ -f "/opt/reform-qcacld2/qcacld2-${KERNVER_EXACT}.ko" ]; then
-        echo "I: Found exact match for kernel ${KERNVER_EXACT}" >&2
-        if insmod -f "/opt/reform-qcacld2/qcacld2-${KERNVER_EXACT}.ko"; then
-            echo "I: Successfully loaded exact match driver" >&2
-            return 0
-        else
-            echo "W: Failed to load exact match driver. Try other available driver" >&2
-        fi
+  # Try to load available drivers, starting with the highest version number, until one works
+  for driver in $potential_drivers; do
+    echo "I: Attempting to load wifi driver: $driver" >&2
+    if insmod -f "$driver"; then
+      echo "I: Successfully loaded driver: $driver" >&2
+      return 0
+    else
+      echo "W: Failed to load driver: $driver, trying next" >&2
     fi
+  done
 
-    # Find other potential qcacld2 drivers
-    potential_drivers=$(find /opt/reform-qcacld2/qcacld2-*.ko -maxdepth 1 -type f -print0 | sort -Vzr)
-
-    # Try to load available drivers, starting with the highest version number, until one works
-    for driver in $potential_drivers; do
-        echo "I: Attempting to load wifi driver: $driver" >&2
-        if insmod -f "$driver"; then
-            echo "I: Successfully loaded driver: $driver" >&2
-            return 0
-        else
-            echo "W: Failed to load driver: $driver, trying next" >&2
-        fi
-    done
-
-    echo "E: Failed to load any compatible qcacld2 driver" >&2
-    return 1
+  echo "E: Failed to load any compatible qcacld2 driver" >&2
+  return 1
 
 }
 case "$(cat /proc/device-tree/model)" in
-"MNT Reform 2"|"MNT Reform 2 HDMI")
+  "MNT Reform 2" | "MNT Reform 2 HDMI")
     # Workaround for WM8960 sometimes not coming out of reset
     if [ ! -e /sys/bus/i2c/drivers/wm8960/2-001a ]; then
-      echo 2-001a > /sys/bus/i2c/drivers/wm8960/bind
+      echo 2-001a >/sys/bus/i2c/drivers/wm8960/bind
     fi
     test -e /sys/bus/i2c/drivers/wm8960/2-001a
 
@@ -133,22 +133,22 @@ case "$(cat /proc/device-tree/model)" in
     # /sys/devices/platform/soc@0/30800000.bus/308?0000.serial/308?0000.serial:0/308?0000.serial:0.0/tty/ttymxc?/power/wakeup
     # use `find` to acquire either path
     find /sys/devices/platform/soc@0/30800000.bus/308?0000.serial/ -wholename '*/tty/ttymxc?/power/wakeup' \
-	| while read -r f; do
-		[ -e "$f" ] || continue
-		echo enabled > "$f"
-	done
+      | while read -r f; do
+        [ -e "$f" ] || continue
+        echo enabled >"$f"
+      done
     ;;
-"MNT Reform 2 with BPI-CM4 Module")
+  "MNT Reform 2 with BPI-CM4 Module")
     # Workaround for WM8960 sometimes not coming out of reset
     if [ ! -e /sys/bus/i2c/drivers/wm8960/1-001a ]; then
-      echo 1-001a > /sys/bus/i2c/drivers/wm8960/bind
+      echo 1-001a >/sys/bus/i2c/drivers/wm8960/bind
     fi
     test -e /sys/bus/i2c/drivers/wm8960/1-001a
 
     init_a311d
     init_wm8960
     ;;
-"MNT Reform 2 with LS1028A Module")
+  "MNT Reform 2 with LS1028A Module")
     # Workaround for a DWC3 USB Controller regression
 
     # Assert USB hub reset
@@ -160,7 +160,7 @@ case "$(cat /proc/device-tree/model)" in
     gpioset 2 13=1
 
     # Select "ondemand" CPU frequency scaling governor
-    echo ondemand > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
+    echo ondemand >/sys/devices/system/cpu/cpufreq/policy0/scaling_governor
 
     # the functionality of the dwc3 module depends on the loglevel
     # loglevel=3 makes usb not work
@@ -168,29 +168,29 @@ case "$(cat /proc/device-tree/model)" in
     # https://community.mnt.re/t/no-keyboard-input-with-ls1028-board-and-latest-image/1994/13
     dmesg -n 7
     ;;
-"MNT Pocket Reform with i.MX8MP Module")
+  "MNT Pocket Reform with i.MX8MP Module")
     init_pocket_display
     init_qca9377_wifi || echo "W: init_qca9377_wifi failed" >&2
     init_tlv320aic3100
     ;;
-"MNT Pocket Reform with BPI-CM4 Module")
+  "MNT Pocket Reform with BPI-CM4 Module")
     init_pocket_display
     init_a311d
     init_tlv320aic3100
     ;;
-"MNT Reform 2 with i.MX8MP Module")
+  "MNT Reform 2 with i.MX8MP Module")
     init_wm8960
     init_qca9377_wifi || echo "W: init_qca9377_wifi failed" >&2
     ;;
-"MNT Reform 2 with RCORE RK3588 Module")
+  "MNT Reform 2 with RCORE RK3588 Module")
     init_wm8960
     ;;
-"MNT Pocket Reform with RCORE RK3588 Module")
+  "MNT Pocket Reform with RCORE RK3588 Module")
     init_pocket_display
     ;;
-"MNT Reform Next with RCORE RK3588 Module")
-    ;;
-*)
+  "MNT Reform Next with RCORE RK3588 Module") ;;
+  *)
     echo "E: Your platform $(cat /proc/device-tree/model) is not supported by reform-tools" >&2
     exit 1
+    ;;
 esac
diff --git a/sbin/reform-migrate b/sbin/reform-migrate
--- a/sbin/reform-migrate
+++ b/sbin/reform-migrate
@@ -4,79 +4,80 @@ set -eu
 
 # shellcheck source=/dev/null
 if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
-	. "./machines/$(cat /proc/device-tree/model).conf"
+  . "./machines/$(cat /proc/device-tree/model).conf"
 elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
-	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+  . "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
 else
-	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
-	exit 1
+  echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+  exit 1
 fi
 
 usage_minimal() {
-	echo "Copies the currently running system onto TARGET and run reform-boot-config" >&2
-	echo "to set up /boot on SD-card or eMMC (selected by the --emmc option) to boot" >&2
-	echo "into the newly copied system. TARGET is a partition block device and will" >&2
-	echo "temporarily get mounted by this script." >&2
-	echo >&2
-	echo "Usage: $0 [--help] [--help-full] [--emmc] DEVICE" >&2
-	echo >&2
-	echo "Options:" >&2
-	echo "  DEVICE           Rootfs partition in /dev.">&2
-	echo "  --help           Display this help and exit." >&2
-	echo "  --help-full      Extended device-specific help output." >&2
-	echo "  --emmc           Choose /boot partition on eMMC instead of SD-card." >&2
+  echo "Copies the currently running system onto TARGET and run reform-boot-config" >&2
+  echo "to set up /boot on SD-card or eMMC (selected by the --emmc option) to boot" >&2
+  echo "into the newly copied system. TARGET is a partition block device and will" >&2
+  echo "temporarily get mounted by this script." >&2
+  echo >&2
+  echo "Usage: $0 [--help] [--help-full] [--emmc] DEVICE" >&2
+  echo >&2
+  echo "Options:" >&2
+  echo "  DEVICE           Rootfs partition in /dev." >&2
+  echo "  --help           Display this help and exit." >&2
+  echo "  --help-full      Extended device-specific help output." >&2
+  echo "  --emmc           Choose /boot partition on eMMC instead of SD-card." >&2
 }
 
 usage() {
-	echo "Usage:"
-	if [ "$EMMC_USE" = true ]; then
-		echo "  reform-migrate [--emmc] TARGET"
-	else
-		echo "  reform-migrate TARGET"
-	fi
-	echo ""
-	echo "Mounts TARGET and copies the currently running system to it using rsync. This will"
-	echo "overwrite all existing files in TARGET. At the end, reform-boot-config is run and"
-	if [ "$EMMC_USE" = true ]; then
-		echo "will set up the first partition of the SD-card or eMMC (depending on the --emmc"
-		echo "option) to load your newly copied rootfs and adjust /etc/fstab of TARGET accordingly."
-		echo ""
-		echo "Options:"
-		echo ""
-		echo "      --emmc Record boot preference on eMMC instead of SD card."
-		case "$(cat /proc/device-tree/model)" in "MNT Reform 2"|"MNT Reform 2 HDMI")
-			echo "             This is only useful with SoM dip switch turned off." ;;
-		esac
-	else
-		echo "will set up the first partition of the SD-card to load your newly copied rootfs"
-		echo "and adjust /etc/fstab of TARGET accordingly."
-	fi
-	echo ""
-	echo "Examples:"
-	echo ""
-	if [ "$EMMC_USE" = true ]; then
-		echo "  reform-migrate --emmc /dev/nvme0n1p1"
-		echo "          Mounts the first partition of an NVMe disk and mirrors your system to it."
-		echo "          Configures booting from the first partition on eMMC."
-	fi
-	echo "  reform-migrate /dev/mapper/crypt"
-	echo "          Mounts encrypted disk 'crypt' and mirrors your system to it."
-	echo "          The disk has to be unlocked first with: cryptsetup luksOpen /dev/nvme0n1p1 crypt"
-	echo "          Configures booting from the first partition on the SD-card as --emmc option is missing."
+  echo "Usage:"
+  if [ "$EMMC_USE" = true ]; then
+    echo "  reform-migrate [--emmc] TARGET"
+  else
+    echo "  reform-migrate TARGET"
+  fi
+  echo ""
+  echo "Mounts TARGET and copies the currently running system to it using rsync. This will"
+  echo "overwrite all existing files in TARGET. At the end, reform-boot-config is run and"
+  if [ "$EMMC_USE" = true ]; then
+    echo "will set up the first partition of the SD-card or eMMC (depending on the --emmc"
+    echo "option) to load your newly copied rootfs and adjust /etc/fstab of TARGET accordingly."
+    echo ""
+    echo "Options:"
+    echo ""
+    echo "      --emmc Record boot preference on eMMC instead of SD card."
+    case "$(cat /proc/device-tree/model)" in "MNT Reform 2" | "MNT Reform 2 HDMI")
+      echo "             This is only useful with SoM dip switch turned off."
+      ;;
+    esac
+  else
+    echo "will set up the first partition of the SD-card to load your newly copied rootfs"
+    echo "and adjust /etc/fstab of TARGET accordingly."
+  fi
+  echo ""
+  echo "Examples:"
+  echo ""
+  if [ "$EMMC_USE" = true ]; then
+    echo "  reform-migrate --emmc /dev/nvme0n1p1"
+    echo "          Mounts the first partition of an NVMe disk and mirrors your system to it."
+    echo "          Configures booting from the first partition on eMMC."
+  fi
+  echo "  reform-migrate /dev/mapper/crypt"
+  echo "          Mounts encrypted disk 'crypt' and mirrors your system to it."
+  echo "          The disk has to be unlocked first with: cryptsetup luksOpen /dev/nvme0n1p1 crypt"
+  echo "          Configures booting from the first partition on the SD-card as --emmc option is missing."
 }
 
 if [ $# -ne 1 ] && [ $# -ne 2 ]; then
-	usage
-	exit 1
+  usage
+  exit 1
 fi
 
 if [ "$1" = "--help" ]; then
-	# minimal device-agnostic help output for use with help2man
-	usage_minimal
-	exit 0
+  # minimal device-agnostic help output for use with help2man
+  usage_minimal
+  exit 0
 elif [ "$1" = "--help-full" ]; then
-	usage
-	exit 0
+  usage
+  exit 0
 fi
 
 EMMC=""
@@ -84,41 +85,40 @@ TARGET="$1"
 BOOTPART="${DEV_SD}p1"
 
 if [ "--emmc" = "$1" ]; then
-	if [ "$EMMC_USE" = false ]; then
-		echo "E: writing to eMMC not supported on $(cat /proc/device-tree/model)" >&2
-		exit 1
-	fi
-	EMMC="--emmc"
-	TARGET="$2"
-	BOOTPART="${DEV_MMC}p1"
+  if [ "$EMMC_USE" = false ]; then
+    echo "E: writing to eMMC not supported on $(cat /proc/device-tree/model)" >&2
+    exit 1
+  fi
+  EMMC="--emmc"
+  TARGET="$2"
+  BOOTPART="${DEV_MMC}p1"
 fi
 
 if [ -z "$TARGET" ]; then
-	usage
-	exit 1
+  usage
+  exit 1
 fi
 
-if [ ! -e "$TARGET" ]
-then
-	echo "Error: The partition $TARGET does not exist."
-	exit
+if [ ! -e "$TARGET" ]; then
+  echo "Error: The partition $TARGET does not exist."
+  exit
 fi
 
 if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "$TARGET")" ]; then
-	echo "$TARGET is still in use" >&2
-	exit 1
+  echo "$TARGET is still in use" >&2
+  exit 1
 fi
 
 # check if the new boot is still mounted somewhere
 if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$BOOTPART")" ]; then
-	echo "/dev/$BOOTPART is still mounted somewhere." >&2
-	echo "Please unmount before running this script" >&2
-	exit 1
+  echo "/dev/$BOOTPART is still mounted somewhere." >&2
+  echo "Please unmount before running this script" >&2
+  exit 1
 fi
 
 if [ "$(id -u)" -ne 0 ]; then
-	echo "reform-boot-config has to be run as root / using sudo." >&2
-	exit 1
+  echo "reform-boot-config has to be run as root / using sudo." >&2
+  exit 1
 fi
 
 echo ""
@@ -130,8 +130,8 @@ echo "Before using this script, your target partition has to be formatted. You c
 echo "gnome-disks can also help you set up an encrypted disk. You can also run the following commands for one single"
 echo "partition on NVMe:"
 echo ""
-echo "    parted /dev/nvme0n1 \"mklabel msdos\""
-echo "    parted /dev/nvme0n1 \"mkpart primary ext4 4MiB -1\""
+echo '    parted /dev/nvme0n1 "mklabel msdos"'
+echo '    parted /dev/nvme0n1 "mkpart primary ext4 4MiB -1"'
 echo "    mkfs.ext4 /dev/nvme0n1p1"
 echo ""
 echo "You can also setup an encrypted NVMe SSD by running reform-setup-encrypted-nvme"
@@ -139,7 +139,10 @@ echo ""
 
 # FIXME: mkimage.sh in reform-system-image could write out the exact values into a known location
 echo "Running rsync to copy approximately 3G of data in about 210k files..." >&2
-command -v "rsync" >/dev/null 2>&1 || { echo >&2 "Please install \"rsync\" using: apt install rsync"; exit 1; }
+command -v "rsync" >/dev/null 2>&1 || {
+  echo >&2 'Please install "rsync" using: apt install rsync'
+  exit 1
+}
 
 echo "Trying to mount $TARGET... (if this fails, format the disk/partition as explained above)"
 
@@ -156,10 +159,10 @@ printf "Are you sure you want to proceed? [y/N] "
 read -r response
 
 if [ "$response" != "y" ]; then
-	echo "Exiting."
-	umount "$MOUNTPOINT"
-	trap - EXIT INT TERM
-	exit
+  echo "Exiting."
+  umount "$MOUNTPOINT"
+  trap - EXIT INT TERM
+  exit
 fi
 
 echo "Starting the copy. This can take a while."
diff --git a/sbin/reform-setup-encrypted-nvme b/sbin/reform-setup-encrypted-nvme
--- a/sbin/reform-setup-encrypted-nvme
+++ b/sbin/reform-setup-encrypted-nvme
@@ -2,51 +2,60 @@
 
 set -eu
 
-usage () {
-	echo "Set up the SSD with LUKS encryption containing LVM2 volumes for" >&2
-	echo "swap and the rootfs. Offers to run reform-migrate and " >&2
-	echo "reform-boot-config to set up the initramfs in /boot to load the" >&2
-	echo "rootfs from the encrypted SSD." >&2
-	echo >&2
-	echo "Usage: $0 [--help]" >&2
-	echo >&2
-	echo "Options:" >&2
-	echo "  --help           Display this help and exit." >&2
+usage() {
+  echo "Set up the SSD with LUKS encryption containing LVM2 volumes for" >&2
+  echo "swap and the rootfs. Offers to run reform-migrate and " >&2
+  echo "reform-boot-config to set up the initramfs in /boot to load the" >&2
+  echo "rootfs from the encrypted SSD." >&2
+  echo >&2
+  echo "Usage: $0 [--help]" >&2
+  echo >&2
+  echo "Options:" >&2
+  echo "  --help           Display this help and exit." >&2
 }
 
 if [ "$#" -gt 0 ]; then
-	if [ "$1" != "--help" ]; then
-		echo "E: too many arguments" >&2
-		usage
-		exit 1
-	fi
-	usage
-	exit 0
+  if [ "$1" != "--help" ]; then
+    echo "E: too many arguments" >&2
+    usage
+    exit 1
+  fi
+  usage
+  exit 0
 fi
 
 if [ "$(id -u)" -ne 0 ]; then
-	echo "reform-setup-encrypted-nvme has to be run as root / using sudo."
-	exit
+  echo "reform-setup-encrypted-nvme has to be run as root / using sudo."
+  exit
 fi
 
-command -v "cryptsetup" >/dev/null 2>&1 || { echo >&2 "Please install \"cryptsetup\" using: apt install cryptsetup"; exit 1; }
-command -v "lvchange" >/dev/null 2>&1 || { echo >&2 "Please install \"lvm2\" using: apt install lvm2"; exit 1; }
-command -v "mkfs.ext4" >/dev/null 2>&1 || { echo >&2 "Please install \"e2fsprogs\" using: apt install e2fsprogs"; exit 1; }
+command -v "cryptsetup" >/dev/null 2>&1 || {
+  echo >&2 'Please install "cryptsetup" using: apt install cryptsetup'
+  exit 1
+}
+command -v "lvchange" >/dev/null 2>&1 || {
+  echo >&2 'Please install "lvm2" using: apt install lvm2'
+  exit 1
+}
+command -v "mkfs.ext4" >/dev/null 2>&1 || {
+  echo >&2 'Please install "e2fsprogs" using: apt install e2fsprogs'
+  exit 1
+}
 
 # shellcheck source=/dev/null
 if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
-	. "./machines/$(cat /proc/device-tree/model).conf"
+  . "./machines/$(cat /proc/device-tree/model).conf"
 elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
-	. "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+  . "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
 else
-	echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
-	exit 1
+  echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+  exit 1
 fi
 
 if [ "$DEV_SSD" = "sda" ]; then
-	HUMAN="SATA"
+  HUMAN="SATA"
 else
-	HUMAN="NVMe"
+  HUMAN="NVMe"
 fi
 
 echo "This will ERASE ALL DATA from your $HUMAN SSD."
@@ -57,8 +66,8 @@ printf "Are you sure you want to proceed? [y/N] "
 read -r response
 
 if [ "$response" != "y" ]; then
-	echo "Exiting."
-	exit
+  echo "Exiting."
+  exit
 fi
 
 cleanupvg() { vgchange -an reformvg; }
@@ -68,39 +77,41 @@ error() { echo "$0 FAILED to run" >&2; }
 trap error EXIT INT TERM
 
 if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$DEV_SSD")" ]; then
-	echo "/dev/$DEV_SSD is still in use" >&2
-	exit 1
+  echo "/dev/$DEV_SSD is still in use" >&2
+  exit 1
 fi
 
 # /proc/meminfo contains the sizes in kibibytes
 mem="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo)"
-case "$mem" in *[!0123456789]*|0?*|"")
-	echo "E: unable to acquire total memory from /proc/meminfo" >&2
-	exit 1
+case "$mem" in *[!0123456789]* | 0?* | "")
+  echo "E: unable to acquire total memory from /proc/meminfo" >&2
+  exit 1
+  ;;
 esac
 # convert memory size to gigabytes, rounding up
 mem="$(awk 'BEGIN {printf("%.f",'"$mem"'/1024/1024+0.5)}')"
 # minimum swap size is 4G
 if [ "$mem" -lt 4 ]; then
-	mem=4
+  mem=4
 fi
 
 disksize=$(lsblk -bno SIZE "/dev/$DEV_SSD" | head -1)
-case "$disksize" in *[!0123456789]*|0?*|"")
-	echo "E: unable to acquire disk size of /dev/$DEV_SSD" >&2
-	exit 1
+case "$disksize" in *[!0123456789]* | 0?* | "")
+  echo "E: unable to acquire disk size of /dev/$DEV_SSD" >&2
+  exit 1
+  ;;
 esac
 # convert disk size to gigabytes, rounding down
-disksize="$((disksize/1024/1024/1024))"
+disksize="$((disksize / 1024 / 1024 / 1024))"
 
 # maximum swap size is 5% of disk size
-if [ "$mem" -gt "$((disksize*5/100))" ]; then
-	mem="$((disksize*5/100))"
+if [ "$mem" -gt "$((disksize * 5 / 100))" ]; then
+  mem="$((disksize * 5 / 100))"
 fi
 
 if [ "$mem" -le 1 ]; then
-	echo "E: your disk is too small for swap" >&2
-	exit 1
+  echo "E: your disk is too small for swap" >&2
+  exit 1
 fi
 
 cryptsetup luksFormat "/dev/$DEV_SSD"
@@ -121,49 +132,49 @@ printf "The encrypted %s is now set up. Do you want me to run reform-migrate now
 read -r response
 
 if [ "$response" != "y" ]; then
-	echo "If you want to migrate this system to $HUMAN SSD you can now run:"
-	echo ""
-	echo "echo RESUME=UUID=$SWAPUUID > /etc/initramfs-tools/conf.d/resume"
-	echo "echo reform_crypt UUID=$CRYPTUUID none luks,discard > /etc/crypttab"
-	echo "echo UUID=$SWAPUUID none swap sw 0 0 >> /etc/fstab"
-	echo "cryptsetup luksOpen /dev/$DEV_SSD reform_crypt"
-	echo "vgchange -ay reformvg"
-	echo "reform-migrate /dev/reformvg/root"
-	echo "vgchange -an reformvg"
-	echo "cryptsetup luksClose reform_crypt"
+  echo "If you want to migrate this system to $HUMAN SSD you can now run:"
+  echo ""
+  echo "echo RESUME=UUID=$SWAPUUID > /etc/initramfs-tools/conf.d/resume"
+  echo "echo reform_crypt UUID=$CRYPTUUID none luks,discard > /etc/crypttab"
+  echo "echo UUID=$SWAPUUID none swap sw 0 0 >> /etc/fstab"
+  echo "cryptsetup luksOpen /dev/$DEV_SSD reform_crypt"
+  echo "vgchange -ay reformvg"
+  echo "reform-migrate /dev/reformvg/root"
+  echo "vgchange -an reformvg"
+  echo "cryptsetup luksClose reform_crypt"
 else
-	# we are not really running reform-migrate but imitate what it does
-	# instead because we want to write out some files after the rsync but
-	# before running reform-boot-config
-	ROOTMNT="$(mktemp --tmpdir --directory reform-setup-encrypted-nvme.XXXXXXXXXX)"
-	trap 'umount $ROOTMNT; cleanupvg; cleanupluks; error' EXIT INT TERM
-	mount /dev/reformvg/root "$ROOTMNT"
-	rsync -axHAWXS --numeric-ids --info=progress2 / "$ROOTMNT"
-	echo "RESUME=UUID=$SWAPUUID" > "$ROOTMNT/etc/initramfs-tools/conf.d/resume"
-	echo "reform_crypt UUID=$CRYPTUUID none luks,discard" > "$ROOTMNT/etc/crypttab"
-	echo "UUID=$SWAPUUID none swap sw 0 0" >> "$ROOTMNT/etc/fstab"
-	trap "cleanupvg; cleanupluks; error" EXIT INT TERM
-	umount "$ROOTMNT"
+  # we are not really running reform-migrate but imitate what it does
+  # instead because we want to write out some files after the rsync but
+  # before running reform-boot-config
+  ROOTMNT="$(mktemp --tmpdir --directory reform-setup-encrypted-nvme.XXXXXXXXXX)"
+  trap 'umount $ROOTMNT; cleanupvg; cleanupluks; error' EXIT INT TERM
+  mount /dev/reformvg/root "$ROOTMNT"
+  rsync -axHAWXS --numeric-ids --info=progress2 / "$ROOTMNT"
+  echo "RESUME=UUID=$SWAPUUID" >"$ROOTMNT/etc/initramfs-tools/conf.d/resume"
+  echo "reform_crypt UUID=$CRYPTUUID none luks,discard" >"$ROOTMNT/etc/crypttab"
+  echo "UUID=$SWAPUUID none swap sw 0 0" >>"$ROOTMNT/etc/fstab"
+  trap "cleanupvg; cleanupluks; error" EXIT INT TERM
+  umount "$ROOTMNT"
 
-	emmc_flag=
-	if [ "$EMMC_USE" = true ]; then
-		printf "Your /boot partition will be on eMMC by default. Do you want it on the SD-Card instead? [y/N] "
-		read -r response
-		if [ "$response" != "y" ]; then
-			emmc_flag="--emmc"
-		fi
-	fi
-	ret=0
-	reform-boot-config $emmc_flag /dev/reformvg/root || ret=$?
-	if [ "$ret" -ne 0 ]; then
-		echo "reform-boot-config failed. To re-run it manually, perform the following steps:" >&2
-		echo "    $ cryptsetup luksOpen \"/dev/$DEV_SSD\" reform_crypt" >&2
-		echo "    $ vgchange -ay reformvg" >&2
-		echo "    $ reform-boot-config $emmc_flag /dev/reformvg/root >&2"
-		echo "    $ vgchange -an reformvg" >&2
-		echo "    $ cryptsetup luksClose reform_crypt" >&2
-		exit "$ret"
-	fi
+  emmc_flag=
+  if [ "$EMMC_USE" = true ]; then
+    printf "Your /boot partition will be on eMMC by default. Do you want it on the SD-Card instead? [y/N] "
+    read -r response
+    if [ "$response" != "y" ]; then
+      emmc_flag="--emmc"
+    fi
+  fi
+  ret=0
+  reform-boot-config $emmc_flag /dev/reformvg/root || ret=$?
+  if [ "$ret" -ne 0 ]; then
+    echo "reform-boot-config failed. To re-run it manually, perform the following steps:" >&2
+    echo "    $ cryptsetup luksOpen \"/dev/$DEV_SSD\" reform_crypt" >&2
+    echo "    $ vgchange -ay reformvg" >&2
+    echo "    $ reform-boot-config $emmc_flag /dev/reformvg/root >&2"
+    echo "    $ vgchange -an reformvg" >&2
+    echo "    $ cryptsetup luksClose reform_crypt" >&2
+    exit "$ret"
+  fi
 fi
 
 trap "cleanupluks; error" EXIT INT TERM
