To setup-encrypted-nvme script add optional positional argument
 - allows one to run it on regular files as well

diff --git a/sbin/reform-setup-encrypted-nvme b/sbin/reform-setup-encrypted-nvme
--- a/sbin/reform-setup-encrypted-nvme
+++ b/sbin/reform-setup-encrypted-nvme
@@ -8,20 +8,27 @@ usage() {
   echo "reform-boot-config to set up the initramfs in /boot to load the" >&2
   echo "rootfs from the encrypted SSD." >&2
   echo >&2
-  echo "Usage: $0 [--help]" >&2
+  echo "Usage: $0 [--help] [DEVICE_PATH]" >&2
   echo >&2
   echo "Options:" >&2
   echo "  --help           Display this help and exit." >&2
+  echo >&2
+  echo "Arguments:" >&2
+  echo "  [DEVICE_PATH]    If provided, path to SSD device, or a disk" >&2
+  echo "                   image file to loop into this role. If left" >&2
+  echo "                   empty, a model-specific default is used." >&2
 }
 
-if [ "$#" -gt 0 ]; then
-  if [ "$1" != "--help" ]; then
-    echo "E: too many arguments" >&2
-    usage
-    exit 1
-  fi
+DEVICE_PATH=
+if [ "$#" -ge 1 ] && [ "$1" = "--help" ]; then
   usage
   exit 0
+elif [ "$#" -ge 2 ]; then
+  echo "E: invalid number of arguments" >&2
+  usage
+  exit 1
+elif [ "$#" -eq 1 ]; then
+  DEVICE_PATH="$1"
 fi
 
 if [ "$(id -u)" -ne 0 ]; then
@@ -42,32 +49,43 @@ command -v "mkfs.ext4" >/dev/null 2>&1 || {
   exit 1
 }
 
-# shellcheck source=/dev/null
-if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
-  . "./machines/$(cat /proc/device-tree/model).conf"
-elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
-  . "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+if [ -z "$DEVICE_PATH" ]; then
+  # shellcheck source=/dev/null
+  if [ -e "./machines/$(cat /proc/device-tree/model).conf" ]; then
+    . "./machines/$(cat /proc/device-tree/model).conf"
+  elif [ -e "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf" ]; then
+    . "/usr/share/reform-tools/machines/$(cat /proc/device-tree/model).conf"
+  else
+    echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+    exit 1
+  fi
+  DEVICE_PATH="/dev/$DEV_SSD"
+fi
+
+if [ -b "$DEVICE_PATH" ]; then
+  if [ "$DEV_SSD" = "sda" ]; then
+    HUMAN="SATA SSD"
+  else
+    HUMAN="NVMe SSD"
+  fi
+
+  echo "This will ERASE ALL DATA from your $HUMAN."
+
+  echo ""
+
+  printf "Are you sure you want to proceed? [y/N] "
+  read -r response
+
+  if [ "$response" != "y" ]; then
+    echo "Exiting."
+    exit
+  fi
+elif [ -f "$DEVICE_PATH" ]; then
+  # plain file -- do nothing
+  HUMAN="reguar file"
 else
-  echo "E: unable to find config for $(cat /proc/device-tree/model)" >&2
+  echo "E: $DEVICE_PATH is neither block device nor regular file" >&2
   exit 1
-fi
-
-if [ "$DEV_SSD" = "sda" ]; then
-  HUMAN="SATA"
-else
-  HUMAN="NVMe"
-fi
-
-echo "This will ERASE ALL DATA from your $HUMAN SSD."
-
-echo ""
-
-printf "Are you sure you want to proceed? [y/N] "
-read -r response
-
-if [ "$response" != "y" ]; then
-  echo "Exiting."
-  exit
 fi
 
 cleanupvg() { vgchange -an reformvg; }
@@ -76,8 +94,8 @@ error() { echo "$0 FAILED to run" >&2; }
 
 trap error EXIT INT TERM
 
-if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$DEV_SSD")" ]; then
-  echo "/dev/$DEV_SSD is still in use" >&2
+if [ ! -f "$DEVICE_PATH" ] && [ -n "$(lsblk --noheadings --output=MOUNTPOINT "$DEVICE_PATH")" ]; then
+  echo "$DEVICE_PATH is still in use" >&2
   exit 1
 fi
 
@@ -95,12 +113,17 @@ if [ "$mem" -lt 4 ]; then
   mem=4
 fi
 
-disksize=$(lsblk --nodeps --bytes --noheadings --output=SIZE "/dev/$DEV_SSD")
-case "$disksize" in *[!0123456789]* | 0?* | "")
-  echo "E: unable to acquire disk size of /dev/$DEV_SSD" >&2
-  exit 1
-  ;;
-esac
+if [ -f "$DEVICE_PATH" ]; then
+  disksize="$(stat -c %s "$DEVICE_PATH")"
+else
+  disksize=$(lsblk --nodeps --bytes --noheadings --output=SIZE "$DEVICE_PATH" | head -1)
+  case "$disksize" in *[!0123456789]* | 0?* | "")
+    echo "E: unable to acquire disk size of $DEVICE_PATH" >&2
+    exit 1
+    ;;
+  esac
+fi
+
 # convert disk size to gigabytes, rounding down
 disksize="$((disksize / 1024 / 1024 / 1024))"
 
@@ -114,9 +137,9 @@ if [ "$mem" -le 1 ]; then
   exit 1
 fi
 
-cryptsetup luksFormat "/dev/$DEV_SSD"
+cryptsetup luksFormat "$DEVICE_PATH"
 trap "cleanupluks; error" EXIT INT TERM
-cryptsetup luksOpen "/dev/$DEV_SSD" reform_crypt
+cryptsetup luksOpen "$DEVICE_PATH" reform_crypt
 pvcreate /dev/mapper/reform_crypt
 vgcreate reformvg /dev/mapper/reform_crypt
 trap "cleanupvg; cleanupluks; error" EXIT INT TERM
@@ -125,19 +148,19 @@ mkswap /dev/reformvg/swap
 lvcreate --name root --extents 100%FREE reformvg
 mkfs.ext4 /dev/reformvg/root
 SWAPUUID=$(lsblk --nodeps --noheadings --output=UUID /dev/reformvg/swap)
-CRYPTUUID=$(lsblk --nodeps --noheadings --output=UUID "/dev/$DEV_SSD")
+CRYPTUUID=$(cryptsetup luksUUID "$DEVICE_PATH")
 
 echo ""
 printf "The encrypted %s is now set up. Do you want me to run reform-migrate now as well? [y/N] " "$HUMAN"
 read -r response
 
 if [ "$response" != "y" ]; then
-  echo "If you want to migrate this system to $HUMAN SSD you can now run:"
+  echo "If you want to migrate this system to $HUMAN you can now run:"
   echo ""
   echo "echo RESUME=UUID=$SWAPUUID > /etc/initramfs-tools/conf.d/resume"
   echo "echo reform_crypt UUID=$CRYPTUUID none luks,discard,x-initrd.attach > /etc/crypttab"
   echo "echo UUID=$SWAPUUID none swap sw 0 0 >> /etc/fstab"
-  echo "cryptsetup luksOpen /dev/$DEV_SSD reform_crypt"
+  echo "cryptsetup luksOpen $DEVICE_PATH reform_crypt"
   echo "vgchange -ay reformvg"
   echo "reform-migrate /dev/reformvg/root"
   echo "vgchange -an reformvg"
@@ -168,7 +191,7 @@ else
   reform-boot-config $emmc_flag /dev/reformvg/root || ret=$?
   if [ "$ret" -ne 0 ]; then
     echo "reform-boot-config failed. To re-run it manually, perform the following steps:" >&2
-    echo "    $ cryptsetup luksOpen \"/dev/$DEV_SSD\" reform_crypt" >&2
+    echo "    $ cryptsetup luksOpen \"$DEVICE_PATH\" reform_crypt" >&2
     echo "    $ vgchange -ay reformvg" >&2
     echo "    $ reform-boot-config $emmc_flag /dev/reformvg/root" >&2
     echo "    $ vgchange -an reformvg" >&2
