sbin/reform-hw-setup: prefix messages with type indicator

diff --git a/sbin/reform-hw-setup b/sbin/reform-hw-setup
--- a/sbin/reform-hw-setup
+++ b/sbin/reform-hw-setup
@@ -80,14 +80,14 @@ init_qca9377_wifi() {
     KERNVER_EXACT=$(dpkg-query --show --showformat '${Version}' "linux-image-$(uname -r)")
     modprobe cfg80211
     
-    echo "Try to load exact match wifi driver: ${KERNVER_EXACT}"
+    echo "I: Try to load exact match wifi driver: ${KERNVER_EXACT}" >&2
     if [ -f "/opt/reform-qcacld2/qcacld2-${KERNVER_EXACT}.ko" ]; then
-        echo "Found exact match for kernel ${KERNVER_EXACT}"
+        echo "I: Found exact match for kernel ${KERNVER_EXACT}" >&2
         if insmod "/opt/reform-qcacld2/qcacld2-${KERNVER_EXACT}.ko"; then
-            echo "Successfully loaded exact match driver"
+            echo "I: Successfully loaded exact match driver" >&2
             return 0
         else
-            echo "Failed to load exact match driver. Try other available driver"
+            echo "W: Failed to load exact match driver. Try other available driver" >&2
         fi
     fi
 
@@ -96,16 +96,16 @@ init_qca9377_wifi() {
 
     # Try to load available drivers, starting with the highest version number, until one works
     for driver in $potential_drivers; do
-        echo "Attempting to load wifi driver: $driver"
+        echo "I: Attempting to load wifi driver: $driver" >&2
         if insmod -f "$driver"; then
-            echo "Successfully loaded driver: $driver"
+            echo "I: Successfully loaded driver: $driver" >&2
             return 0
         else
-            echo "Failed to load driver: $driver, trying next"
+            echo "W: Failed to load driver: $driver, trying next" >&2
         fi
     done
 
-    echo "Failed to load any compatible qcacld2 driver"
+    echo "E: Failed to load any compatible qcacld2 driver" >&2
     return 1
 
 }
@@ -184,6 +184,6 @@ case "$(cat /proc/device-tree/model)" in
 "MNT Reform Next with RCORE RK3588 Module")
     ;;
 *)
-    echo "Your platform $(cat /proc/device-tree/model) is not supported by reform-tools" >&2
+    echo "E: Your platform $(cat /proc/device-tree/model) is not supported by reform-tools" >&2
     exit 1
 esac
