sbin/reform-flash-uboot: instead of finding the end of the first free space, find the beginning of the first partition
 - there is not always free space before the first partition
 - the free space, if there is any, can start at different offsets
   depending on gpt vs. msdos
 - better parsing of the parted output allows better error messages

diff --git a/sbin/reform-flash-uboot b/sbin/reform-flash-uboot
--- a/sbin/reform-flash-uboot
+++ b/sbin/reform-flash-uboot
@@ -147,28 +147,85 @@ for dev in "$@"; do
 
   # no further tests for disks without a partition table
   if [ "$(parted --script --machine "$realdev" unit B print 2>/dev/null | grep "^$realdev:" | cut -d: -f 6)" = unknown ]; then
+    echo "I: no partition table found on $realdev" >&2
     continue
   fi
 
-  freeuntil=$(parted --script --machine "$realdev" unit B print free | grep --max-count=1 '^1:1024B:.*:free;')
-  freeuntil=${freeuntil##1:1024B:}
-  freeuntil=${freeuntil%B:*:free;}
-  # The following checks whether the parsed output is a valid integer.
-  # We cannot use [0-9] because that matches on any character (or
-  # possibly multi-character collation element) that sorts in between 0
-  # and 9.
-  # https://lists.gnu.org/archive/html/bug-bash/2021-02/msg00054.html
-  case "$freeuntil" in *[!0123456789]* | 0?* | "")
-    echo "Unexpected parted output"
-    exit 1
-    ;;
-  esac
+  # We need to start the while loop and the checks after in a sub-shell
+  # because otherwise, the variables that are set in the while loop will
+  # not be available to the code afterwards as the pipe creates an implicit
+  # sub-shell of the loop.
+  parted --script --machine "$realdev" unit B print | {
+    firstpartstart=
+    linenum=1
+    while read -r line; do
+      case $linenum in
+        1)
+          if [ "$line" != "BYT;" ]; then
+            echo "E: unexpected first line of parted output. Expected BYT; but got $line" >&2
+            exit 1
+          fi
+          ;;
+        2)
+          case $line in
+            "$realdev:"*:sd/mmc:512:512:msdos:*":;") : ;; # all good
+            "$realdev:"*:sd/mmc:512:512:gpt:*":;") : ;;   # all good
+            *)
+              echo "E: unexpected second line of parted output: $line" >&2
+              exit 1
+              ;;
+          esac
+          ;;
+        3)
+          case $line in
+            *:*B:*B:*B:*:*:*";")
+              firstpartstart=$line
+              firstpartstart=${firstpartstart#*:}
+              firstpartstart=${firstpartstart%B:*B:*B:*:*:*;}
+              # The following checks whether the parsed output is a valid integer.
+              # We cannot use [0-9] because that matches on any character (or
+              # possibly multi-character collation element) that sorts in between 0
+              # and 9.
+              # https://lists.gnu.org/archive/html/bug-bash/2021-02/msg00054.html
+              case "$firstpartstart" in *[!0123456789]* | 0?* | "")
+                echo "E: cannot parse partition start in: $line" >&2
+                exit 1
+                ;;
+              esac
+              ;;
+            *)
+              echo "E: unexpected third line of parted output: $line" >&2
+              exit 1
+              ;;
+          esac
+          ;;
+      esac
+      linenum=$((linenum + 1))
+    done
 
-  if [ "$((UBOOT_OFFSET - FLASHBIN_OFFSET + ubootsize))" -ge "$freeuntil" ]; then
-    echo "the first partition on $dev $realdev starts at $freeuntil and would be overwritten by uboot" >&2
-    echo "make sure that the first $((UBOOT_OFFSET - FLASHBIN_OFFSET + ubootsize)) bytes are free on $realdev" >&2
-    exit 1
-  fi
+    case $linenum in
+      1)
+        echo "E: no output from parted" >&2
+        exit 1
+        ;;
+      2)
+        echo "E: parted only printed its unit header" >&2
+        exit 1
+        ;;
+      3)
+        echo "I: no partition was found on $realdev" >&2
+        exit 0 # this only exits the sub-shell
+        ;;
+    esac
+
+    if [ "$((UBOOT_OFFSET - FLASHBIN_OFFSET + ubootsize))" -ge "$firstpartstart" ]; then
+      echo "the first partition on $dev $realdev starts at $firstpartstart and would be overwritten by uboot" >&2
+      echo "make sure that the first $((UBOOT_OFFSET - FLASHBIN_OFFSET + ubootsize)) bytes are free on $realdev" >&2
+      exit 1
+    fi
+  }
+  # if the sub shell exited with a non-zero exit, then the parent process will
+  # exit as well due to "set -e"
 done
 
 if [ "$EMMC_BOOT" = warn ]; then
