sbin/reform-flash-uboot: rework
 * new --image option for custom flash.bin
 * device agnostic --help output
 * proper cli parsing with getopts
 * allow flashing to devices other than sd or emmc

diff --git a/sbin/reform-flash-uboot b/sbin/reform-flash-uboot
--- a/sbin/reform-flash-uboot
+++ b/sbin/reform-flash-uboot
@@ -5,20 +5,86 @@
 set -eu
 
 usage() {
-  echo "Download latest u-boot for the current platform and update /boot/flash.bin" >&2
-  echo "Then flash u-boot to DEVICE which can be one of the short-hands sd or emmc." >&2
+  echo "Usage: " >&2
+  echo "  reform-flash-uboot [--offline] [--force] [DEVICE...]" >&2
   echo >&2
-  echo "Usage: $0 [--help] [--offline] DEVICE" >&2
+  echo "Download and flash u-boot for the current platform to DEVICE. Unless" >&2
+  echo "the --offline option is given, download latest u-boot to /boot/flash.bin." >&2
+  echo "If one or more DEVICE is given, flash /boot/flash.bin with the correct" >&2
+  echo "offset to DEVICE. The short-hands 'sd' and 'emmc' can be used to flash" >&2
+  echo "u-boot to the SD-card or eMMC, respectively." >&2
   echo >&2
   echo "Options:" >&2
-  echo '  DEVICE           Target device to flash: either "sd" or "emmc"' >&2
-  echo "  --help           Display this help and exit." >&2
-  echo "  --offline        Instead of download u-boot use /boot/flash.bin." >&2
+  echo "  DEVICE       Block device to flash or short-hands 'sd' or 'emmc'" >&2
+  echo "  -h, --help   Display this help and exit." >&2
+  echo "  -i, --image  Custom image (default: /boot/flash.bin). Implies --offline." >&2
+  echo "  --offline    Do not download latest u-boot to /boot/flash.bin." >&2
+  echo "  -f, --force  No user interaction and flash to devices marked as 'warn'" >&2
+  echo "" >&2
 }
 
-if [ "$#" -gt 0 ] && [ "$1" = "--help" ]; then
-  usage
-  exit 0
+nth_arg() {
+  shift "$1"
+  printf "%s" "$1"
+}
+
+OFFLINE=
+FORCE=
+IMAGE=
+while getopts :hfi:-: OPTCHAR; do
+  case "$OPTCHAR" in
+    h)
+      usage
+      exit 0
+      ;;
+    f) FORCE=yes ;;
+    i) IMAGE="$OPTARG" ;;
+    -)
+      case "$OPTARG" in
+        help)
+          usage
+          exit 0
+          ;;
+        force) FORCE=yes ;;
+        image)
+          if [ "$OPTIND" -gt "$#" ]; then
+            echo "E: missing argument for --image" >&2
+            exit 1
+          fi
+          IMAGE="$(nth_arg "$OPTIND" "$@")"
+          OPTIND=$((OPTIND + 1))
+          OFFLINE=yes
+          ;;
+        image=*)
+          IMAGE="${OPTARG#*=}"
+          OFFLINE=yes
+          ;;
+        offline) OFFLINE=yes ;;
+        *)
+          echo "E: unrecognized option: --$OPTARG" >&2
+          exit 1
+          ;;
+      esac
+      ;;
+    ':')
+      echo "E: missing argument for -$OPTARG" >&2
+      exit 1
+      ;;
+    '?')
+      echo "E: unrecognized option -$OPTARG" >&2
+      exit 1
+      ;;
+    *)
+      echo "E: error parsing options" >&2
+      exit 1
+      ;;
+  esac
+done
+shift "$((OPTIND - 1))"
+
+if [ "$(id -u)" -ne 0 ]; then
+  echo "reform-flash-uboot has to be run as root / using sudo."
+  exit 1
 fi
 
 # shellcheck source=/dev/null
@@ -31,75 +97,24 @@ else
   exit 1
 fi
 
-OFFLINE=
-FORCE=
 for dev in "$@"; do
   case $dev in
-    --offline) OFFLINE=yes ;;
-    --force) FORCE=yes ;;
-    emmc)
+    emmc | "/dev/${DEV_MMC}"*)
       if [ "$EMMC_BOOT" = false ]; then
         echo "E: writing uboot to eMMC not supported on $(cat /proc/device-tree/model)" >&2
         exit 1
       fi
       ;;
-    sd)
+    sd | "/dev/${DEV_SD}"*)
       if [ "$SD_BOOT" = false ]; then
         echo "E: writing uboot to SD-Card not supported on $(cat /proc/device-tree/model)" >&2
         exit 1
       fi
       ;;
-    *)
-      echo "E: unknown device target \"$dev\" given." >&2
-      exit 1
-      ;;
   esac
 done
 
-usage() {
-  echo "Usage: " >&2
-  echo "  reform-flash-uboot [--offline] [--force] [device...]" >&2
-  echo "" >&2
-  if [ "$EMMC_BOOT" != false ] && [ "$SD_BOOT" = true ]; then
-    echo "Download and write recent uboot to eMMC or SD-Card." >&2
-  elif [ "$SD_BOOT" = true ]; then
-    echo "Download and write recent uboot to SD-Card." >&2
-  elif [ "$EMMC_BOOT" != false ]; then
-    echo "Download and write recent uboot to eMMC." >&2
-  else
-    echo "Download recent uboot, but update no devices." >&2
-  fi
-  echo "Without arguments only /boot/flash.bin will be updated unless --offline is given." >&2
-  echo "Otherwise, the arguments are the devices onto which to install uboot." >&2
-  echo "These device names are supported:" >&2
-  echo "" >&2
-  if [ "$EMMC_BOOT" != false ]; then
-    if [ "$DEV_MMC_BOOT0" = true ]; then
-      echo "   emmc (${DEV_MMC}boot0)" >&2
-    else
-      echo "   emmc (${DEV_MMC})" >&2
-    fi
-  fi
-  if [ "$SD_BOOT" = true ]; then
-    echo "   sd (${DEV_SD})" >&2
-  fi
-  echo "" >&2
-  echo "The --force allows flashing to targets marked as 'warn' without " >&2
-  echo "interactively asking the user." >&2
-  echo "" >&2
-}
-
-if [ "$#" -gt 0 ] && [ "$1" = "--help" ] || [ "$#" -gt 0 ] && [ "$1" = "-h" ]; then
-  usage
-  exit 0
-fi
-
-if [ "$(id -u)" -ne 0 ]; then
-  echo "reform-flash-uboot has to be run as root / using sudo."
-  exit 1
-fi
-
-if [ "$#" -eq 0 ] || [ "$OFFLINE" != "yes" ]; then
+if [ "$OFFLINE" != "yes" ]; then
   if echo "$UBOOT_SHA1  /boot/flash.bin" | sha1sum --strict --check >/dev/null 2>&1; then
     echo "/boot/flash.bin is up-to-date -- not downloading it again" >&2
   else
@@ -120,14 +135,6 @@ if [ "$#" -eq 0 ] || [ "$OFFLINE" != "yes" ]; then
     fi
     ;;
   esac
-elif [ "$#" -gt 0 ] && [ "$OFFLINE" = "yes" ]; then
-  echo "Not downloading uboot but using /boot/flash.bin without updating it." >&2
-  shift
-  if ! echo "$UBOOT_SHA1  /boot/flash.bin" | sha1sum --strict --check >/dev/null 2>&1; then
-    echo "Incorrect checksum for /boot/flash.bin" >&2
-    echo "Either flash manually, or run without --offline to download the latest uboot version" >&2
-    exit 1
-  fi
 fi
 
 if [ "$#" -eq 0 ]; then
@@ -135,12 +142,26 @@ if [ "$#" -eq 0 ]; then
   exit 0
 fi
 
-ubootsize=$(stat --format=%s "/boot/flash.bin")
+if [ -z "$IMAGE" ]; then
+  if ! echo "$UBOOT_SHA1  /boot/flash.bin" | sha1sum --strict --check >/dev/null 2>&1; then
+    echo "Incorrect checksum for /boot/flash.bin" >&2
+    echo "Either flash a custom image with --image, or run without --offline to download the latest uboot version" >&2
+    exit 1
+  fi
+  IMAGE="/boot/flash.bin"
+fi
+
+if [ ! -e "$IMAGE" ]; then
+  echo "E: $IMAGE does not exist" >&2
+  exit 1
+fi
+
+ubootsize=$(stat --format=%s "$IMAGE")
 
 # check if there is enough free space at the beginning of the disk
 for dev in "$@"; do
   case $dev in
-    emmc)
+    emmc | "/dev/${DEV_MMC}"*)
       if [ "$DEV_MMC_BOOT0" = true ]; then
         # there are no partitions on boot0, so no need to check here
         continue
@@ -151,7 +172,7 @@ for dev in "$@"; do
     sd)
       realdev=/dev/${DEV_SD}
       ;;
-    *) continue ;;
+    *) realdev="$dev" ;;
   esac
 
   disk_label=$(parted --json --script "$realdev" unit B print 2>/dev/null | jq --raw-output '.disk.label')
@@ -171,7 +192,7 @@ for dev in "$@"; do
   # strip off trailing B
   firstpartstart=${firstpartstart%B}
   if [ "$((UBOOT_OFFSET - FLASHBIN_OFFSET + ubootsize))" -ge "$firstpartstart" ]; then
-    echo "the first partition on $dev $realdev starts at $firstpartstart and would be overwritten by uboot" >&2
+    echo "the first partition on $realdev starts at $firstpartstart and would be overwritten by uboot" >&2
     echo "make sure that the first $((UBOOT_OFFSET - FLASHBIN_OFFSET + ubootsize)) bytes are free on $realdev" >&2
     exit 1
   fi
@@ -179,28 +200,30 @@ done
 
 if [ "$EMMC_BOOT" = warn ] && [ "$FORCE" != "yes" ]; then
   for dev in "$@"; do
-    if [ "$dev" = "emmc" ]; then
-      echo "W: Flashing u-boot to eMMC on $(cat /proc/device-tree/model) is not without risk." >&2
-      echo "W: If you flash the wrong u-boot or if the flashing process goes wrong, it is" >&2
-      echo "W: possible to soft-brick your board. Restoring it might need some extra hardware." >&2
-      echo "W: Please only proceed if you are sure that the benefits outweigh the risks for you." >&2
-      printf "Are you sure you want to proceed? [y/N] "
-      read -r response
+    case $dev in
+      emmc | "/dev/${DEV_MMC}"*)
+        echo "W: Flashing u-boot to eMMC on $(cat /proc/device-tree/model) is not without risk." >&2
+        echo "W: If you flash the wrong u-boot or if the flashing process goes wrong, it is" >&2
+        echo "W: possible to soft-brick your board. Restoring it might need some extra hardware." >&2
+        echo "W: Please only proceed if you are sure that the benefits outweigh the risks for you." >&2
+        printf "Are you sure you want to proceed? [y/N] "
+        read -r response
 
-      if [ "$response" != "y" ]; then
-        echo "Exiting."
-        exit
-      fi
+        if [ "$response" != "y" ]; then
+          echo "Exiting."
+          exit
+        fi
 
-      break
-    fi
+        break
+        ;;
+    esac
   done
 fi
 
 # do the flashing
 for dev in "$@"; do
   case $dev in
-    emmc)
+    emmc | "/dev/${DEV_MMC}"*)
       if [ "$DEV_MMC_BOOT0" = true ]; then
         realdev=/dev/${DEV_MMC}boot0
       else
@@ -210,18 +233,26 @@ for dev in "$@"; do
     sd)
       realdev=/dev/${DEV_SD}
       ;;
-    *) continue ;;
+    *) realdev="$dev" ;;
   esac
 
-  echo "Writing /boot/flash.bin to $dev ($realdev)" >&2
+  echo "Writing $IMAGE to $realdev" >&2
 
-  if [ "$DEV_MMC_BOOT0" = true ] && [ "$dev" = "emmc" ]; then
-    echo 0 >"/sys/class/block/${DEV_MMC}boot0/force_ro"
-  fi
-  dd if=/boot/flash.bin of="$realdev" bs=512 seek="$((UBOOT_OFFSET / 512))" skip="$((FLASHBIN_OFFSET / 512))"
-  if [ "$DEV_MMC_BOOT0" = true ] && [ "$dev" = "emmc" ]; then
-    echo 1 >"/sys/class/block/${DEV_MMC}boot0/force_ro"
-  fi
+  case $dev in
+    emmc | "/dev/${DEV_MMC}"*)
+      if [ "$DEV_MMC_BOOT0" = true ]; then
+        echo 0 >"/sys/class/block/${DEV_MMC}boot0/force_ro"
+      fi
+      ;;
+  esac
+  dd if="$IMAGE" of="$realdev" bs=512 seek="$((UBOOT_OFFSET / 512))" skip="$((FLASHBIN_OFFSET / 512))"
+  case $dev in
+    emmc | "/dev/${DEV_MMC}"*)
+      if [ "$DEV_MMC_BOOT0" = true ]; then
+        echo 1 >"/sys/class/block/${DEV_MMC}boot0/force_ro"
+      fi
+      ;;
+  esac
 
 done
 
@@ -229,12 +260,12 @@ done
 case "$(cat /proc/device-tree/model)" in "MNT Reform 2" | "MNT Reform 2 HDMI")
   for dev in "$@"; do
     case $dev in
-      emmc)
+      emmc | "/dev/${DEV_MMC}"*)
         echo "For the i.MX8MQ to load u-boot from MMC, make sure" >&2
         echo "that your DIP switch is set to OFF." >&2
         continue
         ;;
-      sd)
+      sd | "/dev/${DEV_SD}"*)
         echo "For the i.MX8MQ to load u-boot from SD-Card, make sure" >&2
         echo "that your DIP switch is set to ON." >&2
         continue
