reform-power-daemon: make fw version checks not fatal (complicates testing)

diff --git a/libexec/reform-tools/reform-power-daemon b/libexec/reform-tools/reform-power-daemon
--- a/libexec/reform-tools/reform-power-daemon
+++ b/libexec/reform-tools/reform-power-daemon
@@ -21,7 +21,7 @@ if ! lsmod | grep reform2_lpc; then
 fi
 
 min_sys_ver=20251030
-min_kbd_ver=20251030
+min_kbd_ver=20251118
 sys_ver="$(reform-mcu-tool list --json | jq 'map(select(.device.name == "pocket-sysctl-1.0")) | .[] | .version')"
 kbd_ver="$(reform-mcu-tool list --json | jq 'map(select(.device.name == "pocket-input-1.0")) | .[] | .version')"
 
@@ -29,13 +29,11 @@ echo "System Controller firmware version: $sys_ver"
 echo "Keyboard firmware version: $kbd_ver"
 
 if (( $sys_ver < $min_sys_ver )); then
-	echo "Fatal: Please upgrade your System Controller firmware using gnome-firmware (at least version $min_sys_ver required)." >&2
-	exit 2
+	echo "Warning: Please upgrade your System Controller firmware using gnome-firmware (at least version $min_sys_ver required)." >&2
 fi
 
 if (( $kbd_ver < $min_kbd_ver )); then
-	echo "Fatal: Please upgrade your Keyboard firmware using gnome-firmware (at least version $min_kbd_ver required)." >&2
-	exit 2
+	echo "Warning: Please upgrade your Keyboard firmware using gnome-firmware (at least version $min_kbd_ver required)." >&2
 fi
 
 bat_path="/sys/class/power_supply/BAT0"
